import React, { useState } from 'react';
import contract from '../catalog/business-tables.v1.json';
import tableCases from '../catalog/business-table-cases.v1.json';
import identityCase from '../catalog/identity-flow-case.v1.json';
import './processing-io-card.css';

const number = index => String(index + 1).padStart(2, '0');

const notes = {
  assets: '前 2 行按真实 #2030 账号定义：暂用 X 名称、类别为社交账号、身份待确认；后 3 行说明已确认资产的表格式。这里展示产品定义，尚无后台写入结果。',
  asset_identifiers: '一条资产可有多行标识：Bitcoin 在 #1001 只有一行；CoinGecko ID bitcoin、中文名“比特币”和简称 BTC 在这里指向同一个 asset_id。前 2 个 X 用户 ID 来自真实 #2030 返回；表内映射均为目标案例，尚无后台写入结果。',
  asset_relationships: '这 3 行用于说明资产关系的目标表格式；关系、证据和审核记录尚未核实。',
  asset_monitoring_rules: '这 3 行用于说明监控规则的目标表格式；阈值、状态和审核记录尚未执行。',
  asset_score_events: '规划为各程序先保存详细判定，再将加分事件送入 Redpanda；Redis 保留近期窗口，Delta/Parquet 归档完整流水，二者独立消费。decision_ref 用于回查判定过程。尚无真实写入。',
  asset_scores_current: '以下 5 行为模拟计算案例，时间均为假设，并非后台写入结果。规划以 Redis 保存当前分；本次 Demo 只使用 total_heat 全量热度。#3005 将新资产的起始 +100 按 7 天半衰期衰减，后续贡献可各按自己的规则汇总。排名把分数折算到同一查询时刻。尚无运行中的程序或计算结果。',
};

const notesEn = {
  assets: 'The first two target rows use observed #2030 account names provisionally and remain pending. The other rows show confirmed assets. No backend write is claimed.',
  asset_identifiers: 'One #1001 asset may have multiple identifier rows: CoinGecko ID bitcoin, Chinese name 比特币, and ticker BTC all point to the same Bitcoin asset_id. The first two X IDs were observed in #2030; all mappings are specified case results, not backend writes.',
  asset_relationships: 'These rows specify the target relationship format; the relationships and reviews have not been verified.',
  asset_monitoring_rules: 'These rows specify the target rule format; thresholds and reviews have not been executed.',
  asset_score_events: 'Programs save detailed decisions, then send score events to Redpanda. Independent consumers maintain a recent Redis window and the full Delta/Parquet archive. decision_ref locates the decision. No running write has been observed.',
  asset_scores_current: 'These five rows are illustrative calculations with assumed timestamps, not backend writes. Redis is planned to hold current scores. This demo uses only total_heat. #3005 decays the initial +100 contribution with a seven-day half-life; future contributions may have their own rules. Ranks compare values at one query time. No running job or result exists yet.',
};

function CellValue({ name, value, displayDecimalPlaces }) {
  if (value == null) return <span className="business-table-null">NULL</span>;
  if (typeof value === 'number' && Number.isFinite(value) && displayDecimalPlaces != null) {
    return <code>{value.toFixed(displayDecimalPlaces)}</code>;
  }
  if (name.endsWith('_json')) {
    let formatted = value;
    try { formatted = JSON.stringify(JSON.parse(value), null, 2); } catch { /* Show the stored text. */ }
    return <details className="business-table-json"><summary><code>{value.length > 50 ? `${value.slice(0, 50)}…` : value}</code></summary>
      <pre>{formatted}</pre></details>;
  }
  return <code>{String(value)}</code>;
}

export function BusinessTableCard({ node, language }) {
  const zh = language === 'zh-CN';
  const [caseIndex, setCaseIndex] = useState(0);
  const table = contract.tables[node.name];
  const caseRows = ['assets', 'asset_identifiers'].includes(node.name) ? identityCase.tables[node.name].rows : [];
  const rows = [...caseRows, ...(tableCases.tables[node.name] || [])];
  const scoreAssumptions = node.name === 'asset_scores_current' ? tableCases.score_case_assumptions : null;
  const scoringTable = ['asset_score_events', 'asset_scores_current'].includes(node.name);
  const scoreCase = identityCase.cases[caseIndex];
  const policy = identityCase.initial_score_policy;
  const assetId = scoreCase.create_result.asset_id;
  const decisionRef = policy.decision_ref_template.replace('{asset_id}', assetId);
  const plannedFields = node.name === 'asset_score_events'
    ? [['asset_id', assetId], ['asset_name', scoreCase.create_result.asset_name], ['event_key', zh ? '待 #3006 稳定生成' : 'To be generated by #3006'],
      ['score_key', policy.input_score_key], ['decision_ref', decisionRef], ['score_delta', `+${policy.score_delta}`],
      ['created_at', zh ? '待评分事件首次接受时确定' : 'To be set on first score-event acceptance'],
      ['decay_policy_ref', policy.decay_policy_ref], ['half_life_minutes', policy.decay.half_life_minutes]]
    : [['asset_id', assetId], ['asset_name', scoreCase.create_result.asset_name], ['score_key', policy.current_score_key],
      ['score_value', zh ? '100 × 2^(-实际经过分钟数 / 10080)，显示两位小数' : '100 × 2^(-actual_elapsed_minutes / 10080), display to two decimals'],
      ['calculated_at', zh ? '待 #3005 首次实际计算时确定' : 'To be set by #3005 on first calculation']];
  return <div className="business-table-card">
    <div className="business-table-schema-scroll" role="region" aria-label={zh ? '原表数据' : 'Table rows'}><table className="business-table-raw">
      <thead><tr>{table.columns.map(column => <th key={column.name} title={zh ? column.label_zh : column.name}><code>{column.name}</code></th>)}</tr></thead>
      <tbody>{rows.map(row => <tr key={table.primary_key.map(key => row[key]).join(':')}>
        {table.columns.map(column => <td key={column.name}><CellValue name={column.name} value={row[column.name]} displayDecimalPlaces={column.display_decimal_places} /></td>)}
      </tr>)}</tbody>
    </table></div>
    <div className="business-table-afterword">
    {scoreAssumptions && <p className="processing-io-case-caption">{zh ? '模拟案例 · 假设每个资产仅收到一次 +100，半衰期 7 天，统一在 2026-10-15 00:00 UTC 计算；不是实际评分。' : 'Illustrative cases · assume one +100 event per asset, a seven-day half-life, and a common calculation time of 2026-10-15 00:00 UTC. These are not actual scores.'}</p>}
      <p><strong>{rows.length} {zh ? '行产品案例' : 'product case rows'}</strong> · {zh ? notes[node.name] : notesEn[node.name]}</p>
      {scoreAssumptions && <p className="processing-io-case-caption">{zh ? '假设的事件入账时间：' : 'Assumed event entry times: '}{scoreAssumptions.events.map(event => `${event.asset_name}: ${event.assumed_created_at}`).join('；')}</p>}
      {scoringTable && <div className="processing-input-source">
        <label className="source-case-inspector-picker">{zh ? '贯通案例 · 目标表行' : 'Through-line case · intended table row'}
          <select value={caseIndex} onChange={event => setCaseIndex(Number(event.target.value))}>{identityCase.cases.map((item, index) =>
            <option value={index} key={item.source_record.id}>{index + 1} · {item.source_record.name} · @{item.source_record.username}</option>)}</select></label>
        <p className="processing-io-case-caption">{zh ? node.name === 'asset_score_events'
          ? `#2030 实际返回 ${scoreCase.source_record.name}；若它首次建档，#3008 应将 #5001 的一次 +100 事件归档为下列八项字段，包括 10080 分钟半衰期。当前没有真实 #1005 行，event_key 与入账时间未生成。`
          : `#2030 实际返回 ${scoreCase.source_record.name}；若它首次建档并收到起始 +100，#3005 应写下列当前分。半衰期为 7 天（10080 分钟）；事件入账时间和计算时间尚未确定，所以还没有数值分或真实 #1006 行。`
          : node.name === 'asset_score_events'
            ? `#2030 returned ${scoreCase.source_record.name}. If first created, #3008 should archive one +100 event with all eight fields, including the 10,080-minute half-life. No real #1005 row, event key, or entry time exists.`
            : `#2030 returned ${scoreCase.source_record.name}. If first created and awarded +100, #3005 should write this current-score record. The half-life is seven days (10,080 minutes), but the timestamps are unknown, so there is no numeric value or real #1006 row.`}</p>
        <dl className="source-case-inspector-fields">{plannedFields.map(([name, value], index) => <div key={name}>
          <dt><span className="source-case-field-number">{number(index)}</span><code>{name}</code></dt><dd>{value}</dd>
        </div>)}</dl>
      </div>}
      <details className="business-table-technical"><summary>{zh ? '其他设置 · 字段说明' : 'Other settings · field definitions'}</summary>
        <div className="business-table-schema-scroll"><table>
          <thead><tr><th>#</th><th>{zh ? '字段名' : 'Field name'}</th><th>{zh ? '含义' : 'Meaning'}</th><th>{zh ? '类型' : 'Type'}</th><th>{zh ? '约束' : 'Constraint'}</th></tr></thead>
          <tbody>{table.columns.map((column, index) => {
            const primary = table.primary_key.includes(column.name);
            const unique = table.unique_keys?.find(key => key.includes(column.name));
            const keyLabel = primary ? table.primary_key.length > 1 ? zh ? '联合主键' : 'composite PK' : 'PK'
              : unique ? unique.length > 1 ? zh ? '组合唯一' : 'composite UQ' : 'UQ' : null;
            return <tr key={column.name}><td>{number(index)}</td><td><code>{column.name}</code></td><td>{zh ? column.label_zh : column.name.replaceAll('_', ' ')}</td><td>{column.type}{column.format ? ` · ${column.format.toUpperCase()}` : ''}</td>
              <td>{[keyLabel, column.required ? zh ? '必填' : 'required' : zh ? '可空' : 'nullable'].filter(Boolean).join(' · ')}</td></tr>;
          })}</tbody>
        </table></div>
      </details>
    </div>
  </div>;
}
