import React, { useState } from 'react';
import contract from '../catalog/business-tables.v1.json';
import tableCases from '../catalog/business-table-cases.v1.json';
import identityCase from '../catalog/identity-flow-case.v1.json';
import supabaseSync from '../catalog/supabase-score-sync.v1.json';
import scoreRollup from '../catalog/score-rollup.v1.json';
import './processing-io-card.css';
import { BusinessTableRows } from './BusinessTableRows';
import { TableBackfillCard } from './TableBackfillCard';

const number = index => String(index + 1).padStart(2, '0');

const notes = {
  supabase_asset_scores: '演算案例，非 Supabase 实际记录。只实时写入来源当前前 100 名的变化得分；已有则更新，没有则新增，不存排名。旧资产出榜后不删、不更新，总行数可超过 100。本例新增 KASUN 的 55，保留 Stake | Bonus 的旧分 50。来源版本和同步时间属于待实现的同步协议。',
  assets: '前 2 行按真实 #2030 账号定义：暂用 X 名称、类别为社交账号、身份待确认；后 3 行说明已确认资产的表格式。这里展示产品定义，尚无后台写入结果。',
  asset_identifiers: '一条资产可有多行标识：Bitcoin 在 #1001 只有一行；CoinGecko ID bitcoin、中文名“比特币”和简称 BTC 在这里指向同一个 asset_id。前 2 个 X 用户 ID 来自真实 #2030 返回；表内映射均为目标案例，尚无后台写入结果。',
  asset_relationships: '这 3 行用于说明资产关系的目标表格式；关系、证据和审核记录尚未核实。',
  asset_monitoring_rules: '这 3 行用于说明监控规则的目标表格式；阈值、状态和审核记录尚未执行。',
  asset_score_events: '规划为各程序先保存详细判定，再将加分事件送入 Redpanda；Redis 保留近期窗口，Delta/Parquet 归档完整流水，二者独立消费。decision_ref 用于回查判定过程。尚无真实写入。',
  asset_scores_current: '以下 5 行为模拟计算案例，时间均为假设，并非后台写入结果。当前分由 #3005 定时更新；本次 Demo 只使用 total_heat 全量热度。#3005 将新资产的起始 +100 按 7 天半衰期衰减，后续贡献可各按自己的规则汇总。默认排名读取最近一轮保存的分数。实际回填见下方独立模块。',
};

const notesEn = {
  supabase_asset_scores: 'Illustrative, not observed Supabase records. Immediately upsert changed scores from the source top 100, without a stored rank. Retain old rows after exit, so the target can exceed 100 rows. This case writes KASUN at 55 and keeps Stake | Bonus at its old 50. Version and sync time belong to the proposed protocol.',
  assets: 'The first two target rows use observed #2030 account names provisionally and remain pending. The other rows show confirmed assets. No backend write is claimed.',
  asset_identifiers: 'One #1001 asset may have multiple identifier rows: CoinGecko ID bitcoin, Chinese name 比特币, and ticker BTC all point to the same Bitcoin asset_id. The first two X IDs were observed in #2030; all mappings are specified case results, not backend writes.',
  asset_relationships: 'These rows specify the target relationship format; the relationships and reviews have not been verified.',
  asset_monitoring_rules: 'These rows specify the target rule format; thresholds and reviews have not been executed.',
  asset_score_events: 'Programs save detailed decisions, then send score events to Redpanda. Independent consumers maintain a recent Redis window and the full Delta/Parquet archive. decision_ref locates the decision. No running write has been observed.',
  asset_scores_current: 'These five rows are illustrative calculations with assumed timestamps, not backend writes. Current scores are updated by the scheduled #3005 job. This demo uses only total_heat. #3005 decays the initial +100 contribution with a seven-day half-life; future contributions may have their own rules. Default rankings read the latest stored cycle. Actual backfills appear in the separate module below.',
};

export function BusinessTableCard({ node, language }) {
  const zh = language === 'zh-CN';
  const [caseIndex, setCaseIndex] = useState(0);
  const table = contract.tables[node.name];
  const caseRows = ['assets', 'asset_identifiers'].includes(node.name) ? identityCase.tables[node.name].rows : [];
  const rows = node.name === supabaseSync.target_table ? [...supabaseSync.case.output, ...supabaseSync.case.retained_output] : [...caseRows, ...(tableCases.tables[node.name] || [])];
  const scoreAssumptions = node.name === 'asset_scores_current' ? tableCases.score_case_assumptions : null;
  const scoringTable = ['asset_score_events', 'asset_scores_current'].includes(node.name);
  const scoreCase = identityCase.cases[caseIndex];
  const policy = identityCase.initial_score_policy;
  const assetId = scoreCase.create_result.asset_id;
  const decisionRef = policy.decision_ref_template.replace('{asset_id}', assetId);
  const plannedFields = node.name === 'asset_score_events'
    ? [['asset_id', assetId], ['asset_name', scoreCase.create_result.asset_name], ['event_key', zh ? '待 #3006 稳定生成' : 'To be generated by #3006'],
      ['score_key', policy.input_score_key], ['decision_ref', decisionRef], ['score_delta', `+${policy.score_delta}`],
      ['created_at', zh ? '待评分事件首次接受时确定' : 'To be set on first score-event acceptance'],
      ['decay_policy_ref', policy.decay_policy_ref], ['half_life_minutes', policy.decay.half_life_minutes]]
    : [['asset_id', assetId], ['asset_name', scoreCase.create_result.asset_name], ['score_key', policy.current_score_key],
      ['score_value', zh ? '100 × 2^(-实际经过分钟数 / 10080)，显示两位小数' : '100 × 2^(-actual_elapsed_minutes / 10080), display to two decimals'],
      ['calculated_at', zh ? '待 #3005 首次实际计算时确定' : 'To be set by #3005 on first calculation']];
  return <div className="business-table-card">
    <BusinessTableRows table={table} rows={rows} language={language} />
    <div className="business-table-afterword">
      {scoreAssumptions && <p className="processing-io-case-caption">{zh ? '模拟案例 · 假设每个资产仅收到一次 +100，半衰期 7 天，统一在 2026-10-15 00:00 UTC 计算；不是实际评分。' : 'Illustrative cases · assume one +100 event per asset, a seven-day half-life, and a common calculation time of 2026-10-15 00:00 UTC. These are not actual scores.'}</p>}
      <p><strong>{rows.length} {zh ? scoreAssumptions ? '行设计案例' : '行产品案例' : scoreAssumptions ? 'design case rows' : 'product case rows'}</strong> · {zh ? notes[node.name] : notesEn[node.name]}</p>
        {scoreAssumptions && <p className="processing-io-case-caption">{zh ? '假设的事件入账时间：' : 'Assumed event entry times: '}{scoreAssumptions.events.map(event => `${event.asset_name}: ${event.assumed_created_at}`).join('；')}</p>}
      {node.name === supabaseSync.target_table && <p>{zh ? '案例只列两行，省略另 99 行。#3010 每次只写来源前 100 名，旧记录保留；目标排序可能含旧分，不保证等于来源此刻的榜单。' : 'Only two illustrative rows are shown; 99 are omitted. #3010 writes source top-100 candidates and retains old rows. Sorting this target can include stale scores and need not equal the current source leaderboard.'}</p>}
      {scoringTable && <div className="processing-input-source">
        <label className="source-case-inspector-picker">{zh ? '贯通案例 · 目标表行' : 'Through-line case · intended table row'}
          <select value={caseIndex} onChange={event => setCaseIndex(Number(event.target.value))}>{identityCase.cases.map((item, index) =>
            <option value={index} key={item.source_record.id}>{index + 1} · {item.source_record.name} · @{item.source_record.username}</option>)}</select></label>
        <p className="processing-io-case-caption">{zh ? node.name === 'asset_score_events'
          ? `#2030 实际返回 ${scoreCase.source_record.name}；若它首次建档，#3008 应将 #5001 的一次 +100 事件归档为下列八项字段，包括 10080 分钟半衰期。当前没有真实 #1005 行，event_key 与入账时间未生成。`
          : `#2030 实际返回 ${scoreCase.source_record.name}；若它首次建档并收到起始 +100，#3005 应写下列当前分。半衰期为 7 天（10080 分钟）；事件入账时间和计算时间尚未确定，所以还没有数值分或真实 #1006 行。`
          : node.name === 'asset_score_events'
            ? `#2030 returned ${scoreCase.source_record.name}. If first created, #3008 should archive one +100 event with all eight fields, including the 10,080-minute half-life. No real #1005 row, event key, or entry time exists.`
            : `#2030 returned ${scoreCase.source_record.name}. If first created and awarded +100, #3005 should write this current-score record. The half-life is seven days (10,080 minutes), but the timestamps are unknown, so there is no numeric value or real #1006 row.`}</p>
        <dl className="source-case-inspector-fields">{plannedFields.map(([name, value], index) => <div key={name}>
          <dt><span className="source-case-field-number">{number(index)}</span><code>{name}</code></dt><dd>{value}</dd>
        </div>)}</dl>
      </div>}
      {scoreAssumptions && <p>{zh ? `更新来源：#3005 · 每 ${scoreRollup.configuration.schedule.interval_seconds} 秒重算 #6001 中有评分事件的资产。这里的固定快照按取样与 Git 同步更新。` : `Updated by #3005 every ${scoreRollup.configuration.schedule.interval_seconds} seconds for assets with score events in #6001. This fixed snapshot changes through sampling and Git synchronization.`}</p>}
      {node.name === 'asset_scores_current' && <TableBackfillCard table={table} language={language} />}
      <details className="business-table-technical"><summary>{zh ? '其他设置 · 字段说明' : 'Other settings · field definitions'}</summary>
        <div className="business-table-schema-scroll"><table>
          <thead><tr><th>#</th><th>{zh ? '字段名' : 'Field name'}</th><th>{zh ? '含义' : 'Meaning'}</th><th>{zh ? '类型' : 'Type'}</th><th>{zh ? '约束' : 'Constraint'}</th></tr></thead>
          <tbody>{table.columns.map((column, index) => {
            const primary = table.primary_key.includes(column.name);
            const unique = table.unique_keys?.find(key => key.includes(column.name));
            const keyLabel = primary ? table.primary_key.length > 1 ? zh ? '联合主键' : 'composite PK' : 'PK'
              : unique ? unique.length > 1 ? zh ? '组合唯一' : 'composite UQ' : 'UQ' : null;
            return <tr key={column.name}><td>{number(index)}</td><td><code>{column.name}</code></td><td>{zh ? column.label_zh : column.name.replaceAll('_', ' ')}</td><td>{column.type}{column.format ? ` · ${column.format.toUpperCase()}` : ''}</td>
              <td>{[keyLabel, column.required ? zh ? '必填' : 'required' : zh ? '可空' : 'nullable'].filter(Boolean).join(' · ')}</td></tr>;
          })}</tbody>
        </table></div>
      </details>
    </div>
  </div>;
}
