import React, { useEffect, useState } from 'react';
import { nodeRef, IDENTITY_REFS } from './graphRefs';
import { displayNodeName } from './i18n';
import { displayCatalogNodeName } from './catalogPresentation';
import { displayCaseValue, flattenAccount, SMART_FOLLOWING_OPERATION } from './smartFollowingCase';
import { IdentityPilotStep, MatchedIdentityResult } from './IdentityPilotCase';
import businessTables from '../catalog/business-tables.v1.json';
import tableCases from '../catalog/business-table-cases.v1.json';
import { BusinessTableRows } from './BusinessTableRows';
import scoreRollup from '../catalog/score-rollup.v1.json';
import scoreTopicProposal from '../catalog/score-event-topic-proposal.v1.json';
import identityPilot from '../catalog/identity-flow-case.v1.json';
import publicCalls from '../catalog/public-call-examples.json';
import signalContracts from '../catalog/signal-contracts.v1.json';
import { ProcessingCardFrame } from './ProcessingCardFrame';
import { AssetReviewCase } from './AssetReviewCase';
import './source-case-inspector.css';
import './processing-io-card.css';

const coinGeckoCase = publicCalls.examples.find(item => item.operation_id === 'coingecko.coins_markets');
const turnoverContract = signalContracts.signals.find(item => item.signal_key === 'coingecko_market_turnover_candidate');
const scoreCase = (index, language) => {
  const zh = language === 'zh-CN';
  const selected = identityPilot.cases[index];
  const policy = identityPilot.initial_score_policy;
  const assetId = selected.create_result.asset_id;
  const decisionRef = policy.decision_ref_template.replace('{asset_id}', assetId);
  const eventRows = [
    ['asset_id', assetId], ['asset_name', selected.create_result.asset_name],
    ['event_key', zh ? '待 #3006 按 asset_id + score_key + decision_ref 稳定生成' : 'To be generated by #3006 from asset_id + score_key + decision_ref'],
    ['score_key', policy.input_score_key],
    ['decision_ref', decisionRef],
    ['score_delta', `+${policy.score_delta}`],
    ['created_at', zh ? '待 #3006 首次接受事件时写入 UTC 时间' : 'UTC time to be set by #3006 on first acceptance'],
    ['decay_policy_ref', policy.decay_policy_ref],
    ['half_life_minutes', policy.decay.half_life_minutes],
  ];
  const topicRows = eventRows;
  return { selected, policy, assetId, decisionRef, eventRows, topicRows, cacheRows: topicRows };
};

function CasePicker({ value, setValue, language, label }) {
  return <label className="source-case-inspector-picker">{label}<select value={value} onChange={event => setValue(Number(event.target.value))}>
    {identityPilot.cases.map((item, index) => <option value={index} key={item.source_record.id}>
      {index + 1} · {item.source_record.name} · @{item.source_record.username}</option>)}
  </select></label>;
}

function CaseRows({ rows }) {
  return <dl className="source-case-inspector-fields">{rows.map(([name, value], index) => <div key={name}>
    <dt><span className="source-case-field-number">{String(index + 1).padStart(2, '0')}</span><code>{name}</code></dt>
    <dd>{typeof value === 'string' && value.startsWith('https://') ? <a href={value} target="_blank" rel="noopener noreferrer">{value}</a> : displayCaseValue(value)}</dd>
  </div>)}</dl>;
}

function ScoreTopicHeaders() {
  return <p className="processing-io-case-caption">Headers · {scoreTopicProposal.headers.map((header, index) => <React.Fragment key={header.name}>{index > 0 && ' · '}<code>{header.name}</code> = <code>{header.value}</code></React.Fragment>)}</p>;
}

export function NodeCaseExplanation({ language, purpose, caseSummary, recordGuide, kind = 'node' }) {
  const zh = language === 'zh-CN';
  return <section className="source-case-inspector-explanation node-case-explanation">
    <h3>{zh ? kind === 'table' ? '这张表卡做什么' : '这张节点卡做什么' : kind === 'table' ? 'What this table does' : 'What this node does'}</h3>
    <p>{purpose || (zh ? '这一步的目的尚未说明。' : 'The purpose of this step has not been described.')}</p>
    <h3>{zh ? kind === 'table' ? '目前有哪些记录' : '这次处理到了哪一步' : kind === 'table' ? 'What records exist' : 'What this case shows'}</h3>
    <p>{caseSummary}</p>
    <h3>{zh ? kind === 'table' ? '表记录怎么读' : '所选记录怎么读' : 'How to read the selected record'}</h3>
    <p>{recordGuide}</p>
  </section>;
}

function RedpandaTopicCard({ node, graph, language }) {
  const zh = language === 'zh-CN';
  const scoringProposal = node.reference_number === 5001;
  const [caseIndex, setCaseIndex] = useState(0);
  let settings = {};
  try { settings = JSON.parse(node.notes || '{}'); } catch { /* Keep incomplete designs readable. */ }
  const fields = graph.fields.filter(field => field.node_id === node.id).sort((a, b) => a.ordinal - b.ordinal);
  const headers = scoringProposal ? scoreTopicProposal.headers : settings.headers || [];
  const consumers = Object.entries(settings.consumers || {});
  return <div className="redpanda-topic-card">
    <div className="source-case-inspector-heading"><h3>{zh ? 'Redpanda 数据通道' : 'Redpanda data channel'}</h3><span>{scoringProposal ? zh ? 'Topic 候选 · 尚未批准或创建' : 'Topic candidate · not approved or created' : zh ? '规划 · 尚无真实消息' : 'Planned · no emitted message'}</span></div>
    <dl className="source-case-inspector-fields">
      <div><dt><code>{scoringProposal ? 'topic_candidate' : 'topic'}</code></dt><dd>{scoringProposal ? scoreTopicProposal.topic_choice.candidate : settings.topic || (zh ? '待定义' : 'To define')}</dd></div>
      <div><dt><code>message_key</code></dt><dd>{scoringProposal ? zh ? '不填（当前单 Partition）' : 'Unset (single partition)' : settings.message_key || (zh ? '待定义' : 'To define')}</dd></div>
      {!scoringProposal && <div><dt><code>payload_schema</code></dt><dd>{settings.payload_schema || (zh ? '待定义' : 'To define')}</dd></div>}
    </dl>
    {scoringProposal && <p className="processing-io-case-caption">{zh ? '推荐 score.events 作为唯一新增宽 Topic 候选：已接受的评分贡献需要独立的账本、归档和重放语义；signal.data 保留策略信号语义。候选名仍待 fewunderstand 评审。当前只有一个 Partition，Message Key 留空；Value.data 的 event_key 负责逐笔去重。' : 'score.events is the sole proposed broad Topic candidate for accepted score ledger events; signal.data remains for strategy signals. fewunderstand must review the candidate. The current single-partition demo leaves Message Key unset; event_key in Value.data handles deduplication.'}</p>}
    <div className="message-payload-fields"><strong>{scoringProposal ? 'Value.data' : 'data'} · {fields.length} {zh ? '个已列字段' : 'listed fields'}</strong>
      {fields.map(field => <div key={field.id}><code>{field.name}</code><span>{field.data_type}</span></div>)}
    </div>
    <div className="message-payload-fields"><strong>Headers · {headers.length}</strong>
      {headers.length ? headers.map(header => <div key={header.name}><code>{header.name}</code><span>{header.description || `${header.value} · ${zh ? header.description_zh : header.purpose}`}</span></div>) : <p>{zh ? '尚未定义 Headers。' : 'No headers defined.'}</p>}
    </div>
    {scoringProposal && <p className="processing-io-case-caption">{zh ? '沿用 fewunderstand 的 source / type / category：逻辑业务来源 / 事件家族 / 业务类别。两个 Consumer 各自读后查拟建注册表，再按 Value 结构校验和处理；Redpanda 不在服务端按 Header 筛选。结构版本绑定在注册表，衰减规则引用仍在 Value.data。' : 'Use fewunderstand’s source / type / category convention: logical business origin / event family / business category. Each consumer looks up the proposed registry after read, then validates and handles Value. Redpanda does not filter by header. The registry binds the schema version; the decay policy reference stays in Value.data.'}</p>}
    {node.reference_number === 5001 && <div className="processing-input-source">
      <CasePicker value={caseIndex} setValue={setCaseIndex} language={language} label={zh ? '贯通案例 · 评分事件' : 'Through-line case · score event'} />
      <p className="processing-io-case-caption">{zh ? `#2030 实际返回 ${scoreCase(caseIndex, language).selected.source_record.name}，但 #3009、#3006 尚未执行。下面是候选 Topic 的 Value.data 目标字段，没有真实 Redpanda 消息或 offset。` : `#2030 returned ${scoreCase(caseIndex, language).selected.source_record.name}, but #3009 and #3006 have not run. These are intended Value.data fields for the candidate Topic, not an observed message or offset.`}</p>
      <CaseRows rows={scoreCase(caseIndex, language).topicRows} />
      <ScoreTopicHeaders />
    </div>}
    {node.reference_number === 5002 && <div className="processing-input-source">
      <strong>{zh ? '上游调用案例 · 预计进入 Topic 的数据' : 'Upstream call case · intended Topic data'}</strong>
      <p className="processing-io-case-caption">{zh ? `真实 CoinGecko HTTP 调用（${coinGeckoCase.observed_at}）：请求 ids=bitcoin、vs_currency=usd，返回 1 条。下面只列这次保存的 4 个真实响应字段；其余 Topic 字段没有在该响应样本中保存。没有已验证的 Redpanda 消息，data.id 也不能仅凭请求参数当成实测响应值。` : `A real CoinGecko HTTP call at ${coinGeckoCase.observed_at} requested ids=bitcoin and vs_currency=usd and returned one row. Only four response fields were saved. No Redpanda message was verified, and the requested ID is not an observed data.id.`}</p>
      <CaseRows rows={Object.entries(coinGeckoCase.response)} />
    </div>}
    {node.reference_number === 5003 && <div className="processing-input-source">
      <CasePicker value={caseIndex} setValue={setCaseIndex} language={language} label={zh ? '上游账号案例 · 预计进入 Topic 的 data' : 'Upstream account case · intended Topic data'} />
      <p className="processing-io-case-caption">{zh ? `真实 Kaito MCP 调用 duration=24h，返回 ${identityPilot.source.response_count} 条，这里保存 2 条。以下是原始账号的全部 16 个字段；尚未验证爬虫或 Redpanda 实际发出消息。预计 message_key=data.id=${scoreCase(caseIndex, language).selected.source_record.id}。` : `A real Kaito MCP call returned ${identityPilot.source.response_count} rows for duration=24h; two are saved. All 16 fields of this upstream account follow. Crawler and Redpanda emission are unverified. The intended message key is data.id=${scoreCase(caseIndex, language).selected.source_record.id}.`}</p>
      <CaseRows rows={flattenAccount(scoreCase(caseIndex, language).selected.source_record)} />
    </div>}
    <details className="processing-advanced"><summary>{zh ? '其他设置 · 消费者组' : 'Other settings · consumer groups'}</summary>
      {consumers.length ? consumers.map(([name, group]) => <p key={name}>{name} · <code>{group}</code></p>) : <p>{zh ? '尚未定义消费者组。' : 'No consumer groups defined.'}</p>}
      {scoringProposal && <p>{zh ? '两个独立 Group 各自读取全部事件、按 event_key 幂等写入后才提交自己的 offset；一个 Group 的失败不阻塞另一个。' : 'Each independent group reads all records and commits its own offset only after an idempotent event_key write; one group does not block the other.'}</p>}
    </details>
    {scoringProposal && <details className="processing-advanced"><summary>{zh ? '其他设置 · 现有 Topic 复用分析' : 'Other settings · existing Topic reuse'}</summary>
      {scoreTopicProposal.reuse_assessment.map(item => <p key={item.topics.join(',')}><code>{item.topics.join(', ')}</code> · {zh ? item.reason_zh : item.decision}</p>)}
      <p>{zh ? '具体保留期和 Topic 注册由 fewunderstand 评审；业务要求是归档完成与约定重放期内保留全部已接受事件，不按 asset_id Key 压缩。' : scoreTopicProposal.topic_choice.retention_requirement}</p>
    </details>}
  </div>;
}

function RedisWindowCard({ node, graph, language }) {
  const zh = language === 'zh-CN';
  const [caseIndex, setCaseIndex] = useState(0);
  let settings = {};
  try { settings = JSON.parse(node.notes || '{}'); } catch { /* Keep incomplete designs readable. */ }
  const fields = graph.fields.filter(field => field.node_id === node.id).sort((a, b) => a.ordinal - b.ordinal);
  return <div className="redpanda-topic-card redis-window-card">
    <div className="source-case-inspector-heading"><h3>{zh ? 'Redis 近期数据窗口' : 'Recent Redis data window'}</h3><span>{zh ? '规划 · 尚无真实缓存' : 'Planned · no cached records'}</span></div>
    <dl className="source-case-inspector-fields">
      <div><dt><code>key_pattern</code></dt><dd>{settings.key_pattern || (zh ? '待定义' : 'To define')}</dd></div>
      <div><dt><code>time_index</code></dt><dd>{settings.time_index || (zh ? '待定义' : 'To define')}</dd></div>
      <div><dt><code>retention</code></dt><dd>{settings.retention || (zh ? '待定义' : 'To define')}</dd></div>
    </dl>
    <div className="message-payload-fields"><strong>{zh ? '缓存字段' : 'Cached fields'} · {fields.length}</strong>
      {fields.map(field => <div key={field.id}><code>{field.name}</code><span>{field.data_type}</span></div>)}
    </div>
    <div className="processing-input-source"><CasePicker value={caseIndex} setValue={setCaseIndex} language={language} label={zh ? '贯通案例 · 预期 Redis 记录' : 'Through-line case · intended Redis record'} />
      <p className="processing-io-case-caption">{zh ? `#3007 独立消费 #5001 后，应缓存 ${scoreCase(caseIndex, language).selected.source_record.name} 的这笔起始评分及 Value.data 中的衰减规则引用和半衰期分钟数。event_key、created_at 需沿用实际评分事件；规则版本指向 7 天 / 10080 分钟半衰期。当前尚无消息或真实 Redis 键。` : `After independently consuming #5001, #3007 should cache this initial award for ${scoreCase(caseIndex, language).selected.source_record.name} and its decay policy reference and half-life in Value.data. event_key and created_at must come from the actual score event; the rule version fixes a seven-day / 10,080-minute half-life. No message or Redis key exists yet.`}</p>
      <CaseRows rows={scoreCase(caseIndex, language).cacheRows} /></div>
    <details className="processing-advanced"><summary>{zh ? '其他设置 · 去重与恢复' : 'Other settings · deduplication and recovery'}</summary>
      <p>{zh ? '去重键' : 'Deduplication key'}：<code>{settings.dedupe_key || '—'}</code></p>
      <p>{zh ? '恢复来源' : 'Rebuild source'}：{settings.rebuild_from || '—'}</p>
    </details>
  </div>;
}

// Presentation subset only; the execution contract retains validation and deduplication fields.
const scoreRollupVisibleInputs = {
  assets: ['asset_id', 'name'],
  asset_score_events: ['asset_id', 'asset_name', 'score_delta', 'created_at', 'half_life_minutes'],
};

function ScoreRollupNumericCase({ language, graph, openNode }) {
  const zh = language === 'zh-CN';
  const assumptions = tableCases.score_case_assumptions;
  const policy = identityPilot.initial_score_policy.decay_policy_ref;
  const assets = assumptions.events.map(({ asset_id, asset_name }) => ({ asset_id, name: asset_name }));
  const events = assumptions.events.map(event => ({
    asset_id: event.asset_id, asset_name: event.asset_name,
    event_key: `case:initial:${event.asset_id}`, score_key: 'total_heat',
    decision_ref: `${policy}/${event.asset_id}`, score_delta: assumptions.score_delta,
    created_at: event.assumed_created_at, decay_policy_ref: policy,
    half_life_minutes: assumptions.half_life_minutes,
  }));
  const calculations = events.map(event => {
    const minutes = Math.max(0, (Date.parse(assumptions.calculated_at) - Date.parse(event.created_at)) / 60000);
    return { ...event, minutes, value: event.score_delta * 2 ** (-minutes / event.half_life_minutes) };
  });
  const results = assets.map(asset => ({
    asset_id: asset.asset_id,
    asset_name: events.find(event => event.asset_id === asset.asset_id)?.asset_name ?? null,
    score_key: 'total_heat',
    score_value: calculations.filter(event => event.asset_id === asset.asset_id).reduce((sum, event) => sum + event.value, 0),
    calculated_at: assumptions.calculated_at,
  }));
  const assetTable = { ...businessTables.tables.assets, columns: businessTables.tables.assets.columns.filter(column => scoreRollupVisibleInputs.assets.includes(column.name)) };
  const eventTable = {
    ...businessTables.tables.asset_score_events,
    columns: businessTables.tables.asset_score_events.columns.filter(column => scoreRollupVisibleInputs.asset_score_events.includes(column.name)),
  };
  return <section className="processing-goal-readonly score-rollup-numeric-case">
    <h3>{zh ? '数值案例 · 两张输入表 → 一张结果表' : 'Numeric case · two input tables → one result table'}</h3>
    <p>{zh ? '沿用 #1006 的同一组五个案例。以下资产记录、评分事件和时间均为演算假设，不是后台采集记录；目前只有独立的 #1006 真实结果快照，尚无配套的 #6001 原始事件快照。' : 'The same five cases shown in #1006. Asset rows, events and times are illustrative assumptions, not collected records. A separate actual #1006 snapshot exists, but no paired #6001 event snapshot is available.'}</p>
    <p>{zh ? '本例评分维度 score_key：total_heat；统一计算时刻 calculated_at：' : 'Case score_key: total_heat; common calculated_at: '}<code>{assumptions.calculated_at}</code></p>
    <h4>{zh ? '输入表一 · #1001 资产（本步骤读取的两列）' : 'Input table 1 · #1001 assets (two selected columns)'}</h4>
    <BusinessTableRows table={assetTable} rows={assets} language={language} />
    <h4>{zh ? '输入表二 · #6001 评分事件（计算与输出使用的五列）' : 'Input table 2 · #6001 score events (five columns used for calculation and output)'}</h4>
    <BusinessTableRows table={eventTable} rows={events} language={language} />
    <p>{zh ? '按 asset_id 对应两张表。本例每个资产只有一笔 +100，半衰期均为 10080 分钟；名称和时间可以逐行对照。' : 'Match both tables by asset_id. Each asset has one +100 contribution with a 10,080-minute half-life; compare names and times row by row.'}</p>
    <div className="processing-input-source-heading"><span>{zh ? '查看来源卡片的完整字段：' : 'Full fields on source cards: '}</span>{[1001, 6001].map(ref => {
      const source = graph.nodes.find(item => item.reference_number === ref);
      return source && <button key={ref} onClick={() => openNode(source.id)}>#{ref} {displayNodeName(language, source.name)}</button>;
    })}</div>
    <h4>{zh ? '逐笔计算 · 原始分 → 经过时间 → 剩余贡献' : 'Calculation · original score → elapsed time → remaining contribution'}</h4>
    <ul>{calculations.map(event => <li key={event.event_key}>{event.asset_name}: +{event.score_delta} → {event.minutes} {zh ? '分钟' : 'minutes'} → {event.value.toFixed(2)}</li>)}</ul>
    <h4>{zh ? '输出表 · #1006 当前资产评分' : 'Output table · #1006 current asset scores'}</h4>
    <BusinessTableRows table={businessTables.tables.asset_scores_current} rows={results} language={language} />
    <p>{zh ? '例如 Ethereum：从 10 月 8 日到 10 月 15 日经过 10080 分钟，原始 100 分剩下一半，因此输出 50.00；Solana 经过两个半衰期，输出 25.00。本例没有多笔贡献；若有，则分别衰减后相加，无事件的资产输出 0.00。' : 'Ethereum: October 8 to October 15 is 10,080 minutes, so its original 100 points halve to 50.00. Solana has elapsed two half-lives and yields 25.00. This case has one event per asset; multiple events would decay separately and then sum, while assets without events receive 0.00.'}</p>
  </section>;
}

function ScoreRollupCard({ node, graph, openNode, language }) {
  const zh = language === 'zh-CN';
  const implementationRequest = scoreRollup.implementation_request;
  const requestText = item => item[zh ? 'zh' : 'en'];
  const number = index => String(index + 1).padStart(2, '0');
  const outputColumns = businessTables.tables[scoreRollup.output_table].columns;
  return <><div className="source-case-inspector processing-io-case" aria-label={zh ? '输入与输出' : 'Input and output'}>
    <section className="source-case-inspector-section">
      <div className="source-case-inspector-heading"><h3>{zh ? '输入' : 'Input'}</h3><span>{scoreRollup.inputs.length} {zh ? '项输入 · 资产与评分事件' : 'inputs · assets and score events'}</span></div>
      {scoreRollup.inputs.map(input => {
        const source = graph.nodes.find(item => item.name === (input.source_node || input.table));
        const columns = businessTables.tables[input.table].columns;
        return <div className="processing-input-source" key={input.table}>
          <div className="processing-input-source-heading"><span>{zh ? '来自' : 'From'}</span><button onClick={() => source && openNode(source.id)}>{nodeRef(source)} {input.source_node || input.table}</button></div>
          <p className="processing-io-case-caption">{zh ? input.note_zh : input.note_en}</p>
          <dl className="source-case-inspector-fields">{scoreRollupVisibleInputs[input.table].map((name, index) => {
            const column = columns.find(item => item.name === name);
            return <div key={name}><dt><span className="source-case-field-number">{number(index)}</span><code>{name}</code></dt><dd>{zh ? column?.label_zh : name.replaceAll('_', ' ')}</dd></div>;
          })}</dl>
          <p className="processing-io-case-caption">{zh ? '这里只列本例计算与输出使用的字段；完整字段请点击上方来源卡片。' : 'Only fields used for this case’s calculation and output are listed; open the source card above for the full schema.'}</p>
        </div>;
      })}
    </section>
    <section className="source-case-inspector-section">
      <div className="source-case-inspector-heading"><h3>{zh ? '输出' : 'Output'}</h3><span>{nodeRef(graph.nodes.find(item => item.name === scoreRollup.output_table))} · {zh ? '规划写入' : 'planned write'}</span></div>
      <p className="processing-io-case-caption">{zh ? '以下是 #1006 的输出字段和生成规则；已保存的实际结果快照见 #1006 回填模块。' : 'These are the #1006 output columns and derivation rules. Saved actual results appear in its backfill module.'}</p>
      <dl className="source-case-inspector-fields">{outputColumns.map((column, index) => {
        const rule = scoreRollup.output_fields.find(item => item.name === column.name);
        return <div key={column.name}><dt><span className="source-case-field-number">{number(index)}</span><code>{column.name}</code></dt><dd>{zh ? rule?.rule_zh : rule?.rule_en}</dd></div>;
      })}</dl>
    </section>
  </div><ScoreRollupNumericCase language={language} graph={graph} openNode={openNode} /><section className="processing-goal-readonly execution-trigger" aria-label={zh ? '运行触发' : 'Execution trigger'}>
    <h3>{zh ? '当前实现 · 运行触发' : 'Current implementation · execution trigger'}</h3>
    <CaseRows rows={[
      [zh ? '触发方式' : 'Trigger', zh ? '定时执行' : 'Scheduled'],
      [zh ? '执行频率' : 'Frequency', zh ? `每 ${scoreRollup.configuration.schedule.interval_seconds} 秒一轮` : `Every ${scoreRollup.configuration.schedule.interval_seconds} seconds`],
      [zh ? '计算范围' : 'Scope', zh ? '#1001 全部已登记资产（含待确认身份、无评分事件的资产）' : 'All #1001 registered assets, including pending identities and zero-event assets'],
      [zh ? '计算时刻' : 'Calculation time', zh ? '本轮所有资产使用同一个 UTC 时刻' : 'One UTC instant for every asset in this cycle'],
      [zh ? '写入结果' : 'Output', zh ? '#1006 · total_heat 当前分；无贡献写 0' : '#1006 · current total_heat; zero when no contributions exist'],
      [zh ? '新事件' : 'New events', zh ? '进入 #6001 后由后续定时轮次计入' : 'Included in a scheduled cycle after reaching #6001'],
    ]} />
    <p>{zh ? '没有新事件也会重算衰减；打开页面不触发这项定时任务。' : 'Decay is recalculated even without new events. Opening the page does not trigger this job.'}</p>
    <p>{zh ? '设计已定义；fewunderstand 代码也配置为每分钟。线上调度是否持续正常运行，仍需运行记录核验。' : 'Defined in the design and configured every minute in fewunderstand code. Continuous runtime health still requires execution evidence.'}</p>
    <details className="processing-technical"><summary>{zh ? '定义与实现依据' : 'Design and implementation references'}</summary>
      <p><code>catalog/score-rollup.v1.json → configuration.schedule</code></p>
      <p><code>{scoreRollup.implementation_reference.schedule_file} → serve()</code></p>
    </details>
  </section><section className="processing-goal-readonly execution-trigger" aria-label={zh ? '实现要求' : 'Implementation requirements'}>
    <h3>{zh ? '实现要求 · 待 fewunderstand 实现' : 'Implementation requirements · pending fewunderstand'}</h3>
    <p>{requestText(implementationRequest.summary)}</p>
    <p>{zh ? '新贡献：#3007 写入 #6001 成功 → 触发 #3005。时间衰减：每 60 秒 → 触发同一个 #3005。' : 'New contribution: #3007 updates #6001 → trigger #3005. Time decay: every 60 seconds → trigger the same #3005.'}</p>
    <details className="processing-technical"><summary>{zh ? '实现规则与验收条件' : 'Implementation rules and acceptance criteria'}</summary>
      <h4>{zh ? '实现规则' : 'Requirements'}</h4>
      <ol>{implementationRequest.requirements.map((item, index) => <li key={index}><p>{requestText(item)}</p></li>)}</ol>
      <h4>{zh ? '验收条件' : 'Acceptance criteria'}</h4>
      <ol>{implementationRequest.acceptance.map((item, index) => <li key={index}><p>{requestText(item)}</p></li>)}</ol>
      {implementationRequest.implementation_notes.map((item, index) => <p key={index}>{requestText(item)}</p>)}
      <p>{zh ? 'AI 读取本模块：' : 'AI module source: '}<code>catalog/score-rollup.v1.json → implementation_request</code></p>
      <p>{zh ? '记录日期：' : 'Recorded: '}{implementationRequest.updated_at}</p>
    </details>
  </section><section className="processing-goal-readonly execution-trigger">
    <h3>{zh ? '算法说明 · 用自然语言读公式' : 'Algorithm · the formula in plain language'}</h3>
    <p>{zh ? '先固定本轮的计算时刻，按 asset_id 找到每个资产的所有 total_heat 事件，并按 event_key 去重。对每笔事件，计算从原始入账时间到本轮时刻经过了多少分钟，再用这段时间除以该笔事件的半衰期，得到经过了几个半衰期。每经过一个半衰期，原始贡献就剩下一半；不足一个周期也连续衰减，不等到整天才扣分。若入账时间晚于计算时刻，经过时间按零处理。' : 'Fix one calculation time, match each asset’s total_heat events by asset_id and deduplicate by event_key. Divide elapsed minutes since original entry by that event’s half-life. Each full half-life halves the original contribution; fractional periods decay continuously. Future entry times use zero elapsed minutes.'}</p>
    <p>{zh ? '把同一资产各笔剩余贡献相加，得到当前分；没有事件就记零。半衰期和规则版本沿用原事件参数，计算时校验，不拿上一轮合计分代替原始明细。结果保存同一个 calculated_at，内部保留完整精度，界面显示两位小数；时间经过本身不产生新的负分事件。' : 'Sum the remaining contributions for each asset, or write zero if none exist. Validate and retain each event’s frozen half-life and rule version; do not replace original events with the previous total. Save the common calculated_at and full precision; display two decimals. Time passing creates no negative score event.'}</p>
  </section></>;
}

function ScoreEventConsumerCard({ node, graph, openNode, language }) {
  const zh = language === 'zh-CN';
  const [caseIndex, setCaseIndex] = useState(0);
  const example = scoreCase(caseIndex, language);
  const isRedis = node.reference_number === 3007;
  const targetRef = isRedis ? 6001 : 1005;
  const target = graph.nodes.find(item => item.reference_number === targetRef);
  const topic = graph.nodes.find(item => item.reference_number === 5001);
  return <><CasePicker value={caseIndex} setValue={setCaseIndex} language={language} label={zh ? '贯通案例 · 两路独立消费' : 'Through-line case · independent consumers'} />
    <div className="source-case-inspector processing-io-case" aria-label={zh ? '输入与输出' : 'Input and output'}>
      <section className="source-case-inspector-section"><div className="source-case-inspector-heading"><h3>{zh ? '输入' : 'Input'}</h3><span>{zh ? '预期 Topic 事件' : 'Intended Topic event'}</span></div>
        <div className="processing-input-source"><div className="processing-input-source-heading"><span>{zh ? '来自' : 'From'}</span><button onClick={() => openNode(topic.id)}>{nodeRef(topic)} {topic.name}</button></div>
          <p className="processing-io-case-caption">{zh ? `以真实上游账号 ${example.selected.source_record.name} 为来源。#5001 还没有实际消息，以下是要被两个独立消费者读取的目标事件。` : `Anchored to the observed upstream account ${example.selected.source_record.name}. #5001 has no actual message; this is the intended event for two independent consumers.`}</p>
          <p className="processing-io-case-caption">{zh ? '本步骤逐项保存以下九个字段，因此这些字段都属于本步骤使用的输入。' : 'This step persists all nine fields below, so each is a used input.'}</p><CaseRows rows={example.topicRows} /><ScoreTopicHeaders /></div>
      </section>
      <section className="source-case-inspector-section"><div className="source-case-inspector-heading"><h3>{zh ? '输出' : 'Output'}</h3><span>{zh ? '本消费者的目标记录' : 'This consumer’s intended record'}</span></div>
        <div className="processing-input-source"><div className="processing-input-source-heading"><span>{zh ? '送往' : 'To'}</span><button onClick={() => openNode(target.id)}>{nodeRef(target)} {target.name}</button></div>
          <p className="processing-io-case-caption">{zh ? isRedis ? '按 event_key 去重后写入 Redis 的九项字段，供 #3005 后续定时轮次计算。此处展示目标案例。' : '按 event_key 幂等归档九项原始字段到 #1005；沿用事件入账时间，不用归档时间替换。尚无真实表行。' : isRedis ? 'Dedupe by event_key, cache nine fields, make them available to a subsequent #3005 scheduled cycle. This is an intended case.' : 'Archive all nine original fields idempotently by event_key. Keep the score-entry time, not archive time. No real table row exists.'}</p>
          <CaseRows rows={isRedis ? example.cacheRows : example.eventRows} /></div>
      </section>
    </div><NodeCaseExplanation language={language} purpose={node.definition}
      caseSummary={zh ? `#2030 的账号输入真实存在；#5001 发消息、#${node.reference_number} 消费和写入均尚未执行。` : `The #2030 upstream account was observed. #5001 publication, this consumption, and storage have not run.`}
      recordGuide={zh ? isRedis ? 'Redis 从 Value.data 保存 decay_policy_ref 与 half_life_minutes；event_key 和 created_at 必须等真实评分事件确定。重试按 event_key 去重。' : '#1005 保留原评分事件的九项字段，包括衰减规则引用和半衰期分钟数；decision_ref 可追溯判定。重试按 event_key 幂等归档。' : isRedis ? 'Redis stores decay_policy_ref and half_life_minutes from Value.data. event_key and created_at await the actual event; retries dedupe by event_key.' : '#1005 archives all nine event fields, including the frozen decay parameters. decision_ref traces the decision. Archive retries are idempotent by event_key.'} />
  </>;
}

function MarketTurnoverCaseCard({ node, graph, openNode, language }) {
  const zh = language === 'zh-CN';
  const topic = graph.nodes.find(item => item.reference_number === 5002);
  const { total_volume: volume, market_cap: marketCap } = coinGeckoCase.response;
  const ratio = volume / marketCap;
  const threshold = turnoverContract.processing.trigger.conditions.find(item => item.field === 'turnover_ratio_24h').value;
  return <><div className="source-case-inspector processing-io-case" aria-label={zh ? '输入与输出' : 'Input and output'}>
    <section className="source-case-inspector-section"><div className="source-case-inspector-heading"><h3>{zh ? '输入' : 'Input'}</h3><span>{zh ? '上游实测值 · Topic 未验证' : 'Observed upstream values · Topic unverified'}</span></div>
      <div className="processing-input-source"><div className="processing-input-source-heading"><span>{zh ? '预计来自' : 'Intended source'}</span><button onClick={() => openNode(topic.id)}>{nodeRef(topic)} {topic.name}</button></div>
        <p className="processing-io-case-caption">{zh ? `CoinGecko 真实 HTTP 调用于 ${coinGeckoCase.observed_at} 返回 1 条；保存了 4 个字段，这里只列计算使用的成交额和市值。#5002 尚无已验证消息；#3001 实际需要的 id 和 last_updated 不在这条保存的响应中。` : `A real CoinGecko HTTP call at ${coinGeckoCase.observed_at} returned one row. Four fields were saved; only volume and market cap are used here. #5002 has no verified message, and this sample lacks the id and last_updated needed by #3001.`}</p>
        <CaseRows rows={Object.entries(coinGeckoCase.response).filter(([name]) => ['total_volume', 'market_cap'].includes(name))} /></div>
    </section>
    <section className="source-case-inspector-section"><div className="source-case-inspector-heading"><h3>{zh ? '输出' : 'Output'}</h3><span>{zh ? '手工代入设计规则' : 'Apply the design rule to saved values'}</span></div>
      <div className="processing-input-source"><p className="processing-io-case-caption">{zh ? `成交额/市值 = ${volume} / ${marketCap} = ${ratio.toFixed(5)}，低于设计阈值 ${threshold}。即便补齐身份和时间字段，这条样本也不会触发候选；当前没有程序运行或发出的信号。` : `Volume/market cap = ${volume} / ${marketCap} = ${ratio.toFixed(5)}, below the design threshold ${threshold}. Even with identity and time fields, this sample would not trigger a candidate. No program run or signal emission exists.`}</p>
        <CaseRows rows={[
          ['turnover_ratio_24h', ratio.toFixed(5)], ['trigger_threshold', threshold],
          ['data.id', zh ? '此响应样本未保存；不能由请求 ids 冒充' : 'Not saved in this response; request ids is not an observed value'],
          ['data.last_updated', zh ? '此响应样本未保存' : 'Not saved in this response'],
          ['candidate', zh ? '预期不触发；不是已验证运行结果' : 'Expected no trigger; not an executed result'],
        ]} /></div>
    </section>
  </div><NodeCaseExplanation language={language} purpose={node.definition}
    caseSummary={zh ? '这只验证了保存的两个数可以代入公式；没有 #5002 消息、完整必需输入、真实计算运行或候选产出。阈值仍是待验证的设计选择。' : 'Only the saved numbers can be substituted into the formula. There is no #5002 message, complete input, executed calculation, or candidate output. The threshold remains unvalidated.'}
    recordGuide={zh ? '本例只用成交额和市值计算比例，完整响应请查看来源卡片。请求参数 ids=bitcoin 只能说明查询了什么，不能证明响应中的 data.id。' : 'Only volume and market cap are used for this ratio; the full response is on the source card. The requested ids=bitcoin says what was queried, not what data.id the saved response contained.'} /></>;
}

function InitialScoreCard({ node, graph, openNode, language }) {
  const zh = language === 'zh-CN';
  const [caseIndex, setCaseIndex] = useState(0);
  const policy = identityPilot.initial_score_policy;
  const selected = identityPilot.cases[caseIndex];
  const account = selected.source_record;
  const source = reference => graph.nodes.find(item => item.reference_number === reference);
  const link = reference => {
    const target = source(reference);
    return <button onClick={() => target && openNode(target.id)}>{nodeRef(target)} {target?.name || '—'}</button>;
  };
  const field = (name, value, index) => <div key={name}><dt><span className="source-case-field-number">{String(index + 1).padStart(2, '0')}</span><code>{name}</code></dt><dd>{value}</dd></div>;
  const created = selected.create_result;
  const eventFields = [
    ['asset_id', created.asset_id], ['asset_name', created.asset_name],
    ['score_key', policy.input_score_key],
    ['decision_ref', policy.decision_ref_template.replace('{asset_id}', created.asset_id)],
    ['score_delta', `+${policy.score_delta}`],
    ['decay_policy_ref', policy.decay_policy_ref],
    ['half_life_minutes', policy.decay.half_life_minutes],
  ];
  return <><label className="source-case-inspector-picker">{zh ? '真实上游账号案例' : 'Observed upstream account case'}
    <select value={caseIndex} onChange={event => setCaseIndex(Number(event.target.value))}>{identityPilot.cases.map((item, index) =>
      <option value={index} key={item.source_record.id}>{index + 1} · {item.source_record.name} · @{item.source_record.username}</option>)}</select>
  </label><div className="source-case-inspector processing-io-case" aria-label={zh ? '输入与输出' : 'Input and output'}>
    <section className="source-case-inspector-section"><div className="source-case-inspector-heading"><h3>{zh ? '输入' : 'Input'}</h3><span>{zh ? '两条资产路径汇合' : 'Two asset routes converge'}</span></div>
      <div className="processing-input-source"><div className="processing-input-source-heading"><span>{zh ? '新建路径 · 规定交接' : 'Created route · planned handoff'}</span>{link(3002)}</div><p className="processing-io-case-caption">{zh ? '若 #1002 查无这个 X ID，#3002 应先完成 #1001/#1002 建档，再交以下值；这些不是实际写入结果。' : 'If #1002 has no mapping for this X ID, #3002 should create #1001/#1002 records before passing these values. No write has been observed.'}</p>
        <dl className="source-case-inspector-fields">{[['asset_id', created.asset_id], ['asset_name', created.asset_name], ['action', created.action]].map(([name, value], index) => field(name, value, index))}</dl></div>
      <div className="processing-input-source"><div className="processing-input-source-heading"><span>{zh ? '已有路径 · 规定交接' : 'Existing route · planned handoff'}</span>{link(3004)}</div><p className="processing-io-case-caption">{zh ? '若这个 X ID 已有映射，#3004 应传原 asset_id 与 action=reused；这一路不重新发起起始加分。尚无实际查表结果。' : 'If this X ID is already mapped, #3004 should pass the existing asset_id and action=reused. No initial award is sent. No table lookup has run.'}</p>
        <dl className="source-case-inspector-fields">{[['asset_id', selected.repeat_result.asset_id], ['asset_name', selected.repeat_result.asset_name], ['action', selected.repeat_result.action]].map(([name, value], index) => field(name, value, index))}</dl></div>
    </section>
    <section className="source-case-inspector-section"><div className="source-case-inspector-heading"><h3>{zh ? '输出' : 'Output'}</h3><span>{zh ? '按新建 / 已有分支' : 'By created / existing route'}</span></div>
      <div className="processing-input-source"><div className="processing-input-source-heading"><span>{zh ? '仅新建时送往' : 'Only on creation to'}</span>{link(3006)}</div>
        <p className="processing-io-case-caption">{zh ? `对 ${account.name}，仅在首次建档成功时，#3009 向 total_heat 交付起始 +100 的评分决定；#3006 补齐 event_key、首次接受的 created_at，再向 #5001 的候选通道提交 Value.data 九项字段。三个 Header 标识逻辑业务来源、事件家族和业务类别；尚无真实评分事件。` : `For ${account.name}, only first creation makes #3009 submit an initial +100 contribution to total_heat. #3006 adds event_key and the first-acceptance created_at, then proposes nine Value.data fields for #5001. Three headers identify logical business origin, event family, and business category. No score event has been emitted.`}</p>
        <dl className="source-case-inspector-fields">{eventFields.map(([name, value], index) => field(name, value, index))}</dl>
      </div>
      <div className="processing-input-source"><strong>{zh ? '已有资产：不提交起始事件' : 'Existing asset: no initial event'}</strong><p className="processing-io-case-caption">{zh ? '已有资产不新增起始贡献，原有 total_heat 仍随时间衰减；这里不产生新的 #1005 流水。旧资产缺分要单独补录，不能在每次命中时自动加 100。' : 'An existing asset receives no new initial contribution; its total_heat continues to decay. No new #1005 event is produced here. A missing legacy score needs a separate backfill, never an automatic 100-point award on every match.'}</p></div>
    </section>
  </div><NodeCaseExplanation language={language} purpose={node.definition}
    caseSummary={zh ? `真实观测到 #2030 返回账号 ${account.name}（X ID ${account.id}）。#1002 查表、#3002 建档、#3009 评分及 #3006 发消息都尚未执行；这里展示该账号走两种分支时的规定结果。` : `#2030 returned ${account.name} (X ID ${account.id}). The #1002 lookup, #3002 asset creation, #3009 award, and #3006 publish have not run; the branches show intended outcomes.`}
    recordGuide={zh ? `这个例子的 X ID 和账号名来自真实上游返回；asset_id 是规定的目标值。只有 action=created 会给 ${policy.input_score_key} 加 ${policy.score_delta}，然后按 ${policy.decay_policy_ref} 从入账时刻起连续指数衰减，半衰期为 7 天。action=reused 不重复加分。` : `The X ID and account name are observed; asset_id is a planned value. Only action=created awards ${policy.score_delta} to ${policy.input_score_key}, then decays smoothly from its entry time under ${policy.decay_policy_ref} with a seven-day half-life. action=reused does not re-award.`} /></>;
}

function ScoreEventPublisherCard({ node, graph, openNode, language }) {
  const zh = language === 'zh-CN';
  const [caseIndex, setCaseIndex] = useState(0);
  const selected = identityPilot.cases[caseIndex];
  const account = selected.source_record;
  const policy = identityPilot.initial_score_policy;
  const assetId = selected.create_result.asset_id;
  const decisionRef = policy.decision_ref_template.replace('{asset_id}', assetId);
  const link = reference => {
    const target = graph.nodes.find(item => item.reference_number === reference);
    return <button onClick={() => target && openNode(target.id)}>{nodeRef(target)} {target?.name || '—'}</button>;
  };
  const fields = rows => <dl className="source-case-inspector-fields">{rows.map(([name, value], index) =>
    <div key={name}><dt><span className="source-case-field-number">{String(index + 1).padStart(2, '0')}</span><code>{name}</code></dt><dd>{value}</dd></div>)}</dl>;
  return <><label className="source-case-inspector-picker">{zh ? '起始评分案例' : 'Initial-score case'}
    <select value={caseIndex} onChange={event => setCaseIndex(Number(event.target.value))}>{identityPilot.cases.map((item, index) =>
      <option value={index} key={item.source_record.id}>{index + 1} · {item.source_record.name} · @{item.source_record.username}</option>)}</select>
  </label><div className="source-case-inspector processing-io-case" aria-label={zh ? '输入与输出' : 'Input and output'}>
    <section className="source-case-inspector-section"><div className="source-case-inspector-heading"><h3>{zh ? '输入' : 'Input'}</h3><span>{zh ? '具体评分决定示例' : 'Concrete score-decision example'}</span></div>
      <div className="processing-input-source"><div className="processing-input-source-heading"><span>{zh ? '来自' : 'From'}</span>{link(3009)}</div>
        <p className="processing-io-case-caption">{zh ? `以 #2030 实际返回的 ${account.name}（X ID ${account.id}）为来源；以下是首次建档成功后 #3009 应提交的决定，并非真实已提交记录。已有资产不向 #3006 提交起始评分。` : `Based on the observed #2030 account ${account.name} (X ID ${account.id}). This is the decision #3009 should submit after first creation, not an observed submission. Existing assets send no initial award.`}</p>
        {fields([['asset_id', assetId], ['asset_name', selected.create_result.asset_name], ['score_key', policy.input_score_key], ['score_delta', `+${policy.score_delta}`], ['decision_ref', decisionRef], ['decay_policy_ref', policy.decay_policy_ref], ['half_life_minutes', policy.decay.half_life_minutes]])}</div>
    </section>
    <section className="source-case-inspector-section"><div className="source-case-inspector-heading"><h3>{zh ? '输出' : 'Output'}</h3><span>{zh ? '目标评分事件' : 'Target score event'}</span></div>
      <div className="processing-input-source"><div className="processing-input-source-heading"><span>{zh ? '送往' : 'To'}</span>{link(5001)}</div>
        <p className="processing-io-case-caption">{zh ? '稳定生成 event_key 与首次接受时间；重试沿用。decay_policy_ref 与 half_life_minutes 是 Value.data 中这笔贡献冻结的规则版本和数值参数。尚无实际发布的消息，Topic 名仍待评审。' : 'Generate a stable event_key and first-acceptance time, reusing both on retries. decay_policy_ref and half_life_minutes are frozen with this contribution in Value.data. No message has been published; the Topic name awaits review.'}</p>
        {fields([['asset_id', assetId], ['asset_name', selected.create_result.asset_name], ['event_key', zh ? '待按 asset_id + score_key + decision_ref 稳定生成' : 'To be generated from asset_id + score_key + decision_ref'], ['score_key', policy.input_score_key], ['decision_ref', decisionRef], ['score_delta', `+${policy.score_delta}`], ['created_at', zh ? '待首次接受事件时写入 UTC 时间' : 'UTC time on first acceptance'], ['decay_policy_ref', policy.decay_policy_ref], ['half_life_minutes', policy.decay.half_life_minutes]])}
        <ScoreTopicHeaders /></div>
    </section>
  </div><NodeCaseExplanation language={language} purpose={node.definition}
    caseSummary={zh ? `这条真实上游账号只提供案例来源；#3009 的起始评分决定及 #3006 的事件发布均未执行。#3006 也可接收以后其他评分规则的决定。` : `The observed upstream account anchors this case. Neither #3009's decision nor #3006's publication has run. #3006 may also accept other scoring rules later.`}
    recordGuide={zh ? 'asset_id 和 decision_ref 是当前案例规定的目标值；event_key 与 created_at 必须在首次实际提交时生成，不能拿 #2030 的采集时间冒充入账时间。' : 'asset_id and decision_ref are planned values. event_key and created_at must be produced on first actual submission; the #2030 observation time is not the score-entry time.'} /></>;
}

export function ProcessingIOCard(props) {
  const { node } = props;
  const content = <ProcessingCardContent key={node.id} {...props} />;
  if (['Redpanda Topic', 'Redis Window'].includes(node.type) || node.name === scoreRollup.node.name) return content;
  return <ProcessingCardFrame {...props}>{content}</ProcessingCardFrame>;
}

function ProcessingCardContent({ node, graph, openNode, language, nodeLabel, purpose }) {
  if (node.type === 'Redpanda Topic') {
    return <RedpandaTopicCard node={node} graph={graph} openNode={openNode} language={language} />;
  }
  if (node.type === 'Redis Window') {
    return <RedisWindowCard node={node} graph={graph} openNode={openNode} language={language} />;
  }
  if (node.name === scoreRollup.node.name) {
    return <ScoreRollupCard node={node} graph={graph} openNode={openNode} language={language} />;
  }
  if ([3007, 3008].includes(node.reference_number)) {
    return <ScoreEventConsumerCard node={node} graph={graph} openNode={openNode} language={language} />;
  }
  if ([3003, 4002, 4003].includes(node.reference_number)) {
    return <AssetReviewCase node={node} graph={graph} openNode={openNode} language={language} />;
  }
  if (node.reference_number === 3001) {
    return <MarketTurnoverCaseCard node={node} graph={graph} openNode={openNode} language={language} />;
  }
  if (node.reference_number === identityPilot.initial_score_policy.processing_card) {
    return <InitialScoreCard node={node} graph={graph} openNode={openNode} language={language} />;
  }
  if (node.reference_number === 3006) {
    return <ScoreEventPublisherCard node={node} graph={graph} openNode={openNode} language={language} />;
  }
  if (node.type === 'Flow Result' && node.reference_number === IDENTITY_REFS.matched) {
    return <MatchedIdentityResult node={node} graph={graph} openNode={openNode} language={language} />;
  }
  if (node.reference_number === IDENTITY_REFS.lookup || node.reference_number === IDENTITY_REFS.create) {
    return <IdentityPilotStep node={node} graph={graph} openNode={openNode} language={language} purpose={purpose} />;
  }
  const zh = language === 'zh-CN';
  const incoming = graph.edges.filter(edge => edge.downstream_id === node.id)
    .sort((a, b) => (a.reference_number ?? Infinity) - (b.reference_number ?? Infinity));
  const fields = graph.fields.filter(field => field.node_id === node.id).sort((a, b) => a.ordinal - b.ordinal);
  const fieldById = new Map(graph.fields.map(field => [field.id, field]));
  const inputs = incoming.map(edge => {
    const source = graph.nodes.find(item => item.id === edge.upstream_id);
    const producerEdge = source?.type === 'Redpanda Topic' ? graph.edges.find(item => item.downstream_id === source.id) : null;
    const origin = producerEdge ? graph.nodes.find(item => item.id === producerEdge.upstream_id) : source;
    const usages = graph.field_usages.filter(usage => usage.edge_id === edge.id);
    return { edge, source, origin, isTable: Boolean(source?.is_system_state), fields: usages.map(usage => fieldById.get(usage.source_field_id)).filter(Boolean).sort((a, b) => a.ordinal - b.ordinal) };
  });
  const inputFieldCount = inputs.reduce((count, input) => count + input.fields.length, 0);
  const isSmartFollowing = inputs.some(input => input.origin?.name === SMART_FOLLOWING_OPERATION);
  const [observedCase, setObservedCase] = useState(null);
  const [fieldLabels, setFieldLabels] = useState({});
  useEffect(() => {
    if (!isSmartFollowing) return undefined;
    let active = true;
    fetch(`/api/source-cases/v1/${encodeURIComponent(SMART_FOLLOWING_OPERATION)}`)
      .then(response => response.json())
      .then(data => { if (active) setObservedCase(data.cases?.find(item => item.response_complete && Array.isArray(item.response) && item.response.length)); })
      .catch(() => {});
    fetch(`/api/source-contracts/v1/operations/${encodeURIComponent(SMART_FOLLOWING_OPERATION)}`)
      .then(response => response.json())
      .then(data => { if (active) setFieldLabels(Object.fromEntries((data.operation?.fields || []).map(field => [field.path, field.label_zh]))); })
      .catch(() => {});
    return () => { active = false; };
  }, [isSmartFollowing]);
  const example = observedCase?.response?.[0];
  const exampleFields = new Map(flattenAccount(example));
  const caseRows = fields.map(field => [field.name, exampleFields.get(field.name.replace(/^data\./, ''))]);
  const caseIsComplete = isSmartFollowing && Boolean(example);
  const mappingIsComplete = inputFieldCount > 0 && inputs.filter(input => input.origin?.name === SMART_FOLLOWING_OPERATION).every(input => input.fields.length > 0 && input.fields.every(field => exampleFields.has(field.name.replace(/^data\./, ''))));
  const caseLabel = example ? `${example.name || example.username || example.id} · ${observedCase.response.length} ${zh ? '条上游返回中的第 1 条' : 'upstream rows, first shown'}` : null;
  const caseField = ([path, value], index) => <div key={path}><dt><span className="source-case-field-number">{String(index + 1).padStart(2, '0')}</span>{zh && (fieldLabels[path] || (path === 'asset_id' ? '资产 ID' : path === 'asset_name' ? '资产名称' : path === 'match_status' ? '匹配状态' : ''))} <code>{path}</code></dt><dd>{(path === 'asset_id' || path === 'asset_name' || path === 'match_status') && value === undefined ? zh ? '未知（尚未查表，非实际结果）' : 'Unknown (no table lookup; not an observed result)' : typeof value === 'string' && /^https:\/\//.test(value) ? <a href={value} target="_blank" rel="noopener noreferrer">{value}</a> : displayCaseValue(value)}</dd></div>;
  if (caseIsComplete) return <><div className="source-case-inspector processing-io-case" aria-label={zh ? '输入与输出' : 'Input and output'}>
    <section className="source-case-inspector-section"><div className="source-case-inspector-heading"><h3>{zh ? '输入' : 'Input'}</h3><span>{inputs.length} {zh ? '个来源' : 'sources'}</span></div>
      {inputs.map(({ edge, source, origin, isTable, fields: inputFields }) => {
        const sourceName = nodeLabel?.(source?.name) || displayCatalogNodeName(source, language) || displayNodeName(language, source?.name || '');
        const isObservedSource = origin?.name === SMART_FOLLOWING_OPERATION;
        const isIdentifierTable = isTable && source?.name === 'asset_identifiers';
        return <div className="processing-input-source" key={edge.id}>
          <div className="processing-input-source-heading"><span>{zh ? '来自' : 'From'}</span><button onClick={() => source && openNode(source.id)}>{nodeRef(source)} {sourceName}</button></div>
          {isObservedSource ? <><p className="processing-io-case-caption">{caseLabel} · {zh ? '真实上游返回；#4001 尚无实际消费记录。' : 'Observed upstream response; #4001 has no observed consumed record.'}</p>
            <dl className="source-case-inspector-fields">{inputFields.map(field => [field.name, exampleFields.get(field.name.replace(/^data\./, ''))]).map(caseField)}</dl></>
            : isIdentifierTable ? <><p className="processing-io-case-caption">{zh ? '规划读取 asset_identifiers；查询方式和真实表行仍待确认。' : 'Planned asset_identifiers read; lookup method and actual table rows remain unverified.'}</p>
              <dl className="source-case-inspector-fields">
                <div><dt><span className="source-case-field-number">01</span>{zh ? '候选查询值' : 'Candidate lookup value'} <code>data.id</code></dt><dd>{displayCaseValue(example.id)}</dd></div>
                <div><dt><span className="source-case-field-number">02</span>{zh ? '目标字段' : 'Target field'} <code>asset_id</code></dt><dd>{zh ? '未知（尚无表结果）' : 'Unknown (no table result)'}</dd></div>
              </dl></>
              : <><p className="processing-io-case-caption">{isTable ? zh ? '规划读表；尚无实际表行或查询结果。' : 'Planned table read; no observed row or query result.' : zh ? '此路尚无配对的真实输入案例。' : 'No paired observed input case for this source.'}</p>
                {inputFields.length > 0 && <dl className="source-case-inspector-fields">{inputFields.map((field, fieldIndex) => <div key={field.id}><dt><span className="source-case-field-number">{String(fieldIndex + 1).padStart(2, '0')}</span><code>{field.name}</code></dt><dd>{zh ? '待核对' : 'Unverified'}</dd></div>)}</dl>}
                {isTable && edge.transformation && <p className="processing-io-case-note">{edge.transformation}</p>}
              </>}
        </div>;
      })}
    </section>
    <section className="source-case-inspector-section"><div className="source-case-inspector-heading"><h3>{zh ? '输出' : 'Output'}</h3><span>{caseRows.length} {zh ? '个字段 · 规则示意' : 'fields · illustration'}</span></div>
      <p className="processing-io-case-caption">{zh ? '输出结构示意：仅列本步骤声明的输出字段。精确匹配到已有资产时才填 asset_id；当前没有实际查表结果。' : 'Output illustration: only fields declared by this step are listed. Fill asset_id only after an exact existing-asset match; no table result is observed.'}</p>
      <dl className="source-case-inspector-fields">{caseRows.map(caseField)}</dl>
      {!mappingIsComplete && <p className="processing-io-case-note">{zh ? '当前案例字段与图中的字段映射数量不一致；请检查消息与 #4001 定义。' : 'The case fields and saved graph mappings differ; review the message and #4001 definition.'}</p>}
    </section>
  </div><NodeCaseExplanation language={language} purpose={purpose || node.definition}
    caseSummary={zh ? `这里展示 #2030 返回的第 1 条账号记录（${example.name || example.username || example.id}）。#4001 尚无实际消费、查表或处理结果；右侧输出只是结构示意。` : `The first #2030 account row (${example.name || example.username || example.id}) is shown. #4001 has no observed consumption, table lookup, or processed result; the output is a shape illustration.`}
    recordGuide={zh ? '仅展示声明的输入与输出字段；完整账号记录请到来源卡片查看。当前没有实际匹配结果。' : 'Only declared input and output fields are shown; open the source card for the full account. No actual match has been observed.'} /></>;
  const plannedValue = field => field.example_value || (zh ? '尚无实际处理结果' : 'No observed processed result');
  return <><div className="source-case-inspector processing-io-case" aria-label={zh ? '输入与输出' : 'Input and output'}>
    <section className="source-case-inspector-section"><div className="source-case-inspector-heading"><h3>{zh ? '输入' : 'Input'}</h3><span>{inputs.length} {zh ? '个来源' : 'sources'}</span></div>
      {inputs.map(({ edge, source, isTable, fields: inputFields }) => <div className="processing-input-source" key={edge.id}>
        <div className="processing-input-source-heading"><span>{zh ? '来自' : 'From'}</span><button onClick={() => source && openNode(source.id)}>{nodeRef(source)} {nodeLabel?.(source?.name) || displayCatalogNodeName(source, language) || displayNodeName(language, source?.name || '')}</button></div>
        <p className="processing-io-case-caption">{isTable ? zh ? '规划读表；尚无实际表行或查询结果。' : 'Planned table read; no observed row or query result.' : zh ? '此来源尚无配对的真实处理结果。' : 'No paired observed processed result from this source.'}</p>
        {inputFields.length > 0 ? <dl className="source-case-inspector-fields">{inputFields.map((field, index) => <div key={field.id}><dt><span className="source-case-field-number">{String(index + 1).padStart(2, '0')}</span><code>{field.name}</code></dt><dd>{plannedValue(field)}</dd></div>)}</dl>
          : <p className="processing-io-case-note">{edge.rationale || (zh ? '这一路尚未定义输入字段。' : 'No input fields have been defined for this source.')}</p>}
        {isTable && inputFields.length > 0 && edge.rationale && <p className="processing-io-case-note">{edge.rationale}</p>}
      </div>)}
      {inputs.length === 0 && <p className="processing-io-case-caption">{zh ? '尚未连接输入。' : 'No input connected.'}</p>}
    </section>
    <section className="source-case-inspector-section"><div className="source-case-inspector-heading"><h3>{zh ? '输出' : 'Output'}</h3><span>{fields.length} {zh ? '个字段 · 规划示意' : 'fields · illustration'}</span></div>
      <p className="processing-io-case-caption">{zh ? '字段值用于展示预期格式，尚无这一步的真实处理结果。' : 'Values illustrate the expected format; no processed result is observed.'}</p>
      {fields.length > 0 ? <dl className="source-case-inspector-fields">{fields.map((field, index) => <div key={field.id}><dt><span className="source-case-field-number">{String(index + 1).padStart(2, '0')}</span><code>{field.name}</code></dt><dd>{plannedValue(field)}</dd></div>)}</dl>
        : <p className="processing-io-case-caption">{zh ? '尚未定义输出字段。' : 'No output fields defined.'}</p>}
    </section>
  </div><NodeCaseExplanation language={language} purpose={purpose || node.definition}
    caseSummary={zh ? '目前只有输入与输出字段设计，尚无这张节点卡的实际处理案例。' : 'Only input and output fields are designed; no processed case is available for this node.'}
    recordGuide={zh ? '尚无成对的真实输入和处理结果，暂时不能解读某条输出记录。' : 'There is no paired real input and processed result to interpret yet.'} /></>;
}
