// Reviewable product guidance for upstream operations and reference resources. These are proposed
// uses, not claims that a crawler has emitted records or a signal is validated.
// Each entry answers: what to ask, what to supply, what comes back, how to use it,
// and what to check before trusting a result.
export const SOURCE_USAGE_DRAFTS = {
  'binance.usdm.exchangeInfo': {
    ask: '哪些 USDT-M 合约目前可以作为观察对象？',
    input: '获取交易所的合约目录；需要先按交易状态和合约类型筛选，再选择交易对。',
    output: '预期是合约及交易规则目录；本产品尚未盘点这个响应的具体字段。',
    use: '先建立可观察交易对集合，后续行情、持仓和资金费率才有一致的对象范围。',
    check: '核对上架、下架和交易状态的更新；字段未盘点前不把它当成可直接计算的指标。',
  },
  'binance.usdm.globalLongShortAccountRatio': {
    ask: '某个合约的全市场账户偏多还是偏空？',
    input: '选择合约交易对和统计周期或时间范围。',
    output: '各时点的多头账户占比、空头账户占比和多空账户比。',
    use: '观察账户方向是否持续偏移，并与价格和未平仓量放在同一时间窗比较。',
    check: '这是账户比例，不是持仓金额；单个时点的高低不能直接证明交易机会。',
  },
  'binance.usdm.klines': {
    ask: '某个合约最近是上涨、放量还是波动加大？',
    input: '选择合约交易对、K 线周期和起止时间。',
    output: '每根 K 线的开高低收、成交量和时间等行情值。',
    use: '按固定周期计算价格变化、成交量基线和波动范围，为其他信号提供市场背景。',
    check: '先确认 K 线是否已收盘、时间与时区是否对齐，避免重复计算未完成的周期。',
  },
  'binance.usdm.openInterest': {
    ask: '某个合约现在有多少未平仓量？',
    input: '选择一个合约交易对。',
    output: '该合约的当前未平仓量和响应时间。',
    use: '记录快照，再与后续快照比较变化；可和价格一起判断仓位扩张的背景。',
    check: '单次快照没有趋势；核对单位和采样间隔后再计算变化率。',
  },
  'binance.usdm.openInterestHist': {
    ask: '某个合约的未平仓量在过去一段时间如何变化？',
    input: '选择合约交易对、统计周期和时间范围。',
    output: '按时点排列的未平仓量及其价值等历史值。',
    use: '与同周期价格、成交量对齐，找出持仓扩张或收缩的候选时段。',
    check: '区分数量与计价价值，避免把价格变动造成的价值变化当成新增仓位。',
  },
  'binance.usdm.premiumIndex': {
    ask: '某个合约的资金费率和标记价格是否异常？',
    input: '选择合约交易对；按需要定期采样。',
    output: '标记价格、指数价格、最近资金费率、下次结算时间等快照值。',
    use: '对齐结算时间，比较资金费率与价格偏离的变化，提出拥挤交易的候选线索。',
    check: '这是快照和最近费率；不要把最近费率误当成已发生的下一次结算。',
  },
  'binance.usdm.takerlongshortRatio': {
    ask: '某个合约近期主动买入还是主动卖出更强？',
    input: '选择合约交易对和统计周期或时间范围。',
    output: '各时点的主动买量、主动卖量和买卖量比。',
    use: '看主动成交方向是否连续偏移，再与价格和成交量共同解释。',
    check: '主动成交量不是净持仓；先核对统计周期与成交量单位。',
  },
  'binance.usdm.topLongShortAccountRatio': {
    ask: '头部交易账户偏多还是偏空？',
    input: '选择合约交易对和统计周期或时间范围。',
    output: '头部账户的多头占比、空头占比和账户多空比。',
    use: '与全市场账户多空比比较，观察头部账户方向是否分化。',
    check: '这里数的是账户方向，不代表头部账户的持仓规模。',
  },
  'binance.usdm.topLongShortPositionRatio': {
    ask: '头部交易者的持仓方向是否在变化？',
    input: '选择合约交易对和统计周期或时间范围。',
    output: '头部交易者按持仓统计的多空比例及时间。',
    use: '与头部账户多空比并看，区分“人数偏向”和“仓位偏向”。',
    check: '不能把持仓比例解释成具体交易者的买卖动作；先对齐两个比例的口径。',
  },
  'coingecko.coins_markets': {
    ask: '哪些币种的价格、市值或成交量正在变化？',
    input: '选择计价货币，以及币种、类别或列表范围等筛选条件。',
    output: '币种标识、价格、市值、成交量、排名和涨跌幅等市场快照。',
    use: '先用稳定币种 ID 对齐资产，再按相同时间和计价货币比较变化。',
    check: '符号可能重名；列表快照不能替代逐笔行情，且不同计价货币不可直接混算。',
  },
  'dexscreener.token_pairs_by_address': {
    ask: '某条链上的代币在哪些交易对交易，流动性如何？',
    input: '提供链 ID 和代币合约地址。',
    output: '该地址关联的交易对、池地址、价格、流动性和成交情况。',
    use: '先按链、地址和交易对识别对象，再挑选可比较的池观察流动性与交易活跃度。',
    check: '一个代币可能有多个池；低流动性池或同名代币容易造成误判。',
  },
  'kaito.resource.tokens': {
    ask: 'Kaito 支持哪些代币标识？',
    input: '读取 kaito://tokens 参考资源；公开说明标注无需认证。',
    output: '公开说明称包含代币值、符号和项目名称；尚未核对实际返回内容。',
    use: '查询情绪、关注份额或事件之前，先核对对象标识。',
    check: '这是参考目录，不是项目热度或爬虫观测记录；名称和符号仍需消歧。',
  },
  'kaito.resource.narratives': {
    ask: 'Kaito 支持哪些叙事标识？',
    input: '读取 kaito://narratives 参考资源；公开说明标注无需认证。',
    output: '公开说明称包含支持的叙事 ID；尚未核对实际返回内容。',
    use: '查询叙事关注份额前，先确认主题在 Kaito 中对应的标识。',
    check: '这是参考目录，不是叙事热度或爬虫观测记录；分类范围由 Kaito 定义。',
  },
  'kaito.mcp.kaito_entities': {
    ask: '这个项目名或代号在 Kaito 中对应哪个对象？',
    input: '用项目名、代币值、交易符号或 CoinGecko slug 搜索；也可不填以浏览支持列表。',
    output: '候选对象及其 Kaito token、名称、符号和 CoinGecko 标识。',
    use: '先核对身份，再把返回的 token 用于对象情绪、关注份额和事件等查询。',
    check: '同名或同符号可能指不同资产；不要凭名称猜 token 值。',
  },
  'kaito.mcp.kaito_narratives': {
    ask: 'Kaito 对某个叙事主题使用什么标识？',
    input: '按叙事 ID 或显示名称搜索；也可浏览支持的叙事。',
    output: '叙事 ID、名称和说明。',
    use: '确认叙事范围后，用 ID 查询叙事关注份额走势。',
    check: '叙事分类由 Kaito 定义；不能把名称相近的叙事直接合并。',
  },
  'kaito.mcp.kaito_feeds': {
    ask: '最近有哪些值得查看的市场或对象相关内容？',
    input: '可不指定对象看市场动态；若限定对象，先解析 token。可附时间范围和返回条数。',
    output: '排序后的内容条目，可能带摘要、作者、时间、互动量和原文链接。',
    use: '作为发现线索的入口，打开原文后再判断它支持哪个候选事件或研究问题。',
    check: '排名高不等于事实可靠；检查来源、重复内容及对象关联。',
  },
  'kaito.mcp.kaito_search': {
    ask: '关于一个问题，Kaito 能找到哪些相关内容？',
    input: '输入自然语言问题，例如“最近有哪些关于某主题的讨论？”；可限制结果数。',
    output: '相关的帖子、新闻或其他内容条目及来源链接。',
    use: '先搜集候选证据，再按发布时间、作者和原文内容整理线索。',
    check: '搜索结果是内容，不是已核实事件；当前爬虫尚未调用此操作。',
  },
  'kaito.mcp.kaito_advanced_search': {
    ask: '在指定来源、作者或时间内，哪些内容讨论了这个对象或主题？',
    input: '用词语或已解析的 tokens 检索；可加 X 用户名、Twitter/News 来源、时间及排序条件。',
    output: '带作者、发布时间、摘要、互动量和原文链接的内容条目。',
    use: '按明确条件收集证据；若研究某个 X 账户的发帖，使用用户名筛选并核对作者。',
    check: '用户名筛选只适用于 Twitter 来源；当前爬虫的参数写法需与实时 MCP 契约逐项核对。',
  },
  'kaito.mcp.kaito_twitter_user_metadata': {
    ask: '这个 X 用户是谁，账号规模和类型是什么？',
    input: '提供 X 用户 ID。',
    output: '账号名、简介、粉丝数、关注数和账号分类等资料。',
    use: '核实作者身份，为内容或账号分析补充背景。',
    check: '资料是查询时的快照；粉丝数和简介会变化，账号身份仍需人工核对。',
  },
  'kaito.mcp.kaito_ict_impressions': {
    ask: '某位高影响力作者的内容在一段时间获得多少曝光？',
    input: '提供 X 作者 ID 和起止日期。',
    output: '窗口内总曝光量、纳入统计的推文数和作者是否在追踪范围。',
    use: '把总曝光量与发帖数一起看，比较同一作者不同时间窗的触达。',
    check: '先确认作者属于 Kaito 的追踪范围；不可将总曝光量当成独立受众人数。',
  },
  'kaito.mcp.kaito_sentiment_entity': {
    ask: '某个代币相关讨论的情绪如何变化？',
    input: '先解析 token，再给出日期范围；平滑、平均值等口径可选。',
    output: '按日期排列的情绪分数及可能的事件标记。',
    use: '比较同一对象的历史基线，并与互动量、关注份额和事件时间对齐。',
    check: '先固定情绪计算选项；单日分数不能代表事实判断或交易信号。',
  },
  'kaito.mcp.kaito_engagement': {
    ask: '某个代币或普通关键词的讨论互动是否在增加？',
    input: '二选一：已解析的 token，或主题 keyword（如 miracle）；可给起止日期。',
    output: '每天的总互动量与高质量账号互动量。',
    use: '先比较同一查询词在连续日期的变化，再看高质量账号互动占比是否同步变化。',
    check: '关键词可能有歧义；这不是按任意 X 账户统计其自发帖互动的接口。DeFi、miracle 已有直接 MCP 查询结果，爬虫输出未核验。',
  },
  'kaito.mcp.kaito_mentions': {
    ask: '某个代币或主题每天被提到多少次？',
    input: '二选一：已解析的 token，或主题 keyword；可给起止日期。',
    output: '按日期索引的提及次数。',
    use: '与互动量分开看，区分“谈论的人或内容变多”和“每条内容传播更强”。',
    check: '关键词歧义和重复提及会影响解释；样本没有按来源拆分的计数。',
  },
  'kaito.mcp.kaito_mindshare_entity': {
    ask: '某个代币占相关讨论的份额是否上升？',
    input: '先解析 token，再选起止日期；可按接口支持的范围筛选。',
    output: '该对象每天的关注份额。',
    use: '和历史份额及同类对象比较，寻找持续抬升的候选线索。',
    check: '份额是相对量，可能因整体讨论量下降而上升；当前爬虫参数与实时 MCP 要求仍需核对。',
  },
  'kaito.mcp.kaito_mindshare_entity_by_account': {
    ask: '哪些账号最推动某个代币的讨论份额？',
    input: '先解析 token，再选统计窗口和返回的头部账号数。',
    output: '账号排名、用户标识和该账号对对象的关注份额。',
    use: '识别贡献较大的作者，再回看其原文与账号资料。',
    check: '这是账号对特定代币的贡献排名，不是该账号全部内容的互动表现。',
  },
  'kaito.mcp.kaito_events': {
    ask: '某个代币接下来有哪些值得核实的催化事件？',
    input: '先用 kaito_entities 解析 token；可按事件日期、公告日期、类型和来源筛选。',
    output: '候选事件、日期、说明、催化标签及参考资料链接。',
    use: '将每件事作为待核实线索，逐条检查原始公告与时间，再设计提醒。',
    check: '上游候选事件不是下游规则触发的信号事件；当前爬虫的 entity/window/limit 参数与实时 MCP 契约不一致。',
  },
  'kaito.mcp.kaito_mindshare_entity_arena': {
    ask: '当前哪些对象的讨论份额排名靠前？',
    input: '选统计时长；可加语言、类别、Pre-TGE 等筛选。',
    output: '对象名称、代号、关注份额和排名。',
    use: '发现值得进一步研究的候选对象，再查询其长期走势和具体内容。',
    check: '排名依赖筛选范围与统计窗口；上榜不等于近期正在增长。',
  },
  'kaito.mcp.kaito_mindshare_entity_delta': {
    ask: '哪些对象的关注份额在指定窗口上升或下降最多？',
    input: '选择统计时长、上升或下降方向和返回数量。',
    output: '对象、当前份额和份额变化量。',
    use: '做候选发现，再追查变化来自哪些内容或事件。',
    check: '变化排名会受基数和窗口影响；不能只看增幅就认定出现了可靠信号。',
  },
  'kaito.mcp.kaito_smart_following_market': {
    ask: '高关注度账号最近把注意力转向了谁？',
    input: '可选统计时长、排序、分页和账号类型筛选；无需指定单个项目。',
    output: '预期是市场范围内的关注行为或账号列表；当前没有非空返回样本可核对字段。',
    use: '暂作为候选发现入口，拿到非空响应后再确定可用指标和去重方法。',
    check: '已有调用返回空数组；不能据此判断没有关注行为，也不能臆造记录结构。',
  },
  'kaito.mcp.kaito_smart_followers': {
    ask: '某个 X 账号有多少高质量粉丝，指定日期新增了谁？',
    input: '提供 X 用户 ID 或用户名；可选日期以及 count/users 返回模式。',
    output: '高质量粉丝数量，或指定模式下的粉丝名单。',
    use: '观察账号受专业受众关注的变化，并结合账号身份核实。',
    check: '“高质量”由 Kaito 分类；累计数和某日新增名单不能混为一谈。',
  },
  'kaito.mcp.kaito_smart_following': {
    ask: '某个 X 账号最近关注了哪些高质量账号？',
    input: '提供 X 用户 ID 或用户名；可按被关注账号类别筛选。',
    output: '最近关注的账号及类别、时间等信息。',
    use: '作为账号注意力变化的候选线索，再核对被关注者身份。',
    check: '关注动作不等于投资、认可或合作；不能单独触发资产信号。',
  },
  'kaito.mcp.kaito_mindshare_narrative': {
    ask: '某个叙事主题的讨论份额是否在变化？',
    input: '先用 kaito_narratives 确认叙事 ID，再给起止日期。',
    output: '叙事名称及按日期排列的关注份额。',
    use: '比较同一叙事的历史变化，再查看相关对象和内容。',
    check: '叙事份额不是某个项目的份额；定义或覆盖变化要单独核对。',
  },
  'kaito.mcp.kaito_market_sentiment': {
    ask: '加密市场整体讨论情绪如何变化？',
    input: '可选择起始日期和情绪分数口径；无需指定代币。',
    output: '市场情绪分数、日期和市场市值等背景值。',
    use: '为对象情绪提供市场背景，避免把全市场共振误读为单一对象变化。',
    check: '先固定平均值或加权值口径；市场整体值不能代替具体对象的情绪。',
  },
  'kaito.mcp.kaito_tweet_engagement_info': {
    ask: '一条具体 X 推文获得了哪些互动？',
    input: '提供该推文的数字 ID。',
    output: '点赞、回复、转发、引用、浏览和高质量账号互动等计数。',
    use: '核对单条内容的传播表现，再与作者、发布时间和原文一起分析。',
    check: '这是单条推文快照，不是某个账号或主题的整体走势。',
  },
  'rss.item': {
    ask: '订阅的新闻来源最近发布了什么？',
    input: '配置要订阅的 RSS feed；读取其中的新 item。',
    output: '标题、链接、发布时间、摘要和来源等条目。',
    use: '作为新闻线索，按链接和标题去重，并回到原文核对事件内容。',
    check: '摘要可能不完整；发布时间和更新日期、转载与原发需要区分。',
  },
  'taoli.funding_page': {
    ask: '页面展示的资金费率是否值得跟踪？',
    input: '读取 Taoli 页面；具体查询参数和稳定字段尚待第一方接口说明。',
    output: '预期为页面中的资金费率表；目前没有可靠的上游字段契约。',
    use: '先拿到可复核样本和字段口径，再决定是否设计跨交易所比较。',
    check: '页面位置会变；不能把页面解析结果当成已验证的稳定 API。',
  },
  'telegram.bot.message': {
    ask: 'Bot 可访问的群或频道最近讨论了什么？',
    input: '让 Bot 接收已授权聊天中的消息；按聊天和时间范围筛选。',
    output: '消息 ID、聊天、发送者、时间、文字及可能的媒体信息。',
    use: '按聊天和消息 ID 去重，提取候选话题并保留原始消息位置。',
    check: 'Bot 的可见范围受权限限制；转发、媒体和编辑消息需要单独处理。',
  },
  'telegram.telethon.message': {
    ask: '获准访问的 Telegram 频道中出现了哪些相关消息？',
    input: '使用已授权的 Telethon 会话读取指定聊天或频道及时间范围。',
    output: '消息 ID、发送者、时间、正文、媒体及转发或浏览信息。',
    use: '按来源频道和消息 ID 去重，回看原文，再与其他来源的线索关联。',
    check: '账号可见范围和频道权限决定覆盖；浏览数与转发数口径需核对。',
  },
};
