export const INPUT_GROUPS = [
  { title: '查什么', title_en: 'What to search', names: ['query', 'keyword', 'tokens', 'usernames'] },
  { title: '查哪里、查多久', title_en: 'Source and time', names: ['sources', 'languages', 'min_created_at', 'max_created_at'] },
  { title: '怎样排序、翻页', title_en: 'Sorting and paging', names: ['rerank', 'rerank_query', 'sort_by', 'sort_order', 'from', 'size'] },
  { title: '只看哪些 X 内容', title_en: 'X post filters', names: ['tweet_length_type', 'tweet_type', 'sentiment_type', 'author_type'] },
  { title: '按 X 互动数筛选', title_en: 'X engagement thresholds', names: [
    'min_bookmark_count', 'max_bookmark_count', 'min_view_count', 'max_view_count',
    'min_smart_engagement_count', 'max_smart_engagement_count', 'min_like_count',
    'max_like_count', 'min_reply_count', 'max_reply_count', 'min_retweet_count',
    'max_retweet_count', 'min_quote_count', 'max_quote_count',
  ] },
];

export const INPUT_EXPLANATIONS_ZH = {
  query: '输入主要搜索词，建议用 1–6 个关键词；仅用 tokens 就够时可省略。',
  keyword: '另一种主文本查询参数，适合 2–6 个高辨识度词或短语。',
  tokens: '用 Kaito 识别出的对象代号限定主题；多个值用英文逗号分隔，如 BTC,ETH。',
  usernames: '只看指定 X 账号发布的内容；多个用户名用英文逗号分隔，仅用于 Twitter。',
  sources: '选择 Twitter、News 或两者；多个来源用英文逗号分隔，省略时文档默认两者。',
  languages: '用语言代码筛选，如 en、zh；多个值用英文逗号分隔，文档默认 en。',
  min_created_at: '内容发布时间的下界，使用 ISO 8601 时间；文档默认约为调用前 90 天。',
  max_created_at: '内容发布时间的上界，使用 ISO 8601 时间；可与下界组成时间窗口。',
  rerank: '设为 false 时保留原始搜索顺序；是否重排还受其他参数组合影响。',
  rerank_query: '供服务端按研究问题重排相关性。文档要求显式 UTC 日期、relevance 排序、from=0、size≤20。',
  sort_by: '选择排序依据。部分互动、情绪、作者类字段只支持 sources=Twitter。',
  sort_order: 'asc 为升序、desc 为降序；文档默认 desc。',
  from: '翻页起点偏移量，文档范围 0–500，默认 0。',
  size: '请求的结果条数；文档建议重排时设为 1–20、默认 20。但这次实测 size=1 或 2 仍返回 50 条，不能把它当作已验证的返回上限。',
  tweet_length_type: '只看指定长度形态的 X 内容：短帖、长帖、串帖或文章。',
  tweet_type: '只看普通帖、引用帖或回复；仅用于 Twitter。',
  sentiment_type: '按整条帖子的看涨、看跌或中性情绪筛选，不专指某个代币；仅用于 Twitter。',
  author_type: '按作者是组织还是个人筛选；仅用于 Twitter。',
  min_bookmark_count: '收藏数下限；仅用于 Twitter。',
  max_bookmark_count: '收藏数上限；仅用于 Twitter。',
  min_view_count: '浏览数下限；仅用于 Twitter。',
  max_view_count: '浏览数上限；仅用于 Twitter。',
  min_smart_engagement_count: 'Kaito 所称高质量账号互动数的下限；仅用于 Twitter。',
  max_smart_engagement_count: 'Kaito 所称高质量账号互动数的上限；仅用于 Twitter。',
  min_like_count: '点赞数下限；仅用于 Twitter。本次响应没有逐条返回点赞数，无法从结果单独核实是否满足。',
  max_like_count: '点赞数上限；仅用于 Twitter。',
  min_reply_count: '回复数下限；仅用于 Twitter。',
  max_reply_count: '回复数上限；仅用于 Twitter。',
  min_retweet_count: '转发数下限；仅用于 Twitter。',
  max_retweet_count: '转发数上限；仅用于 Twitter。',
  min_quote_count: '引用数下限；仅用于 Twitter。',
  max_quote_count: '每条推文被引用的次数上限；例如填 10，表示只请求引用数不超过 10 的推文，不是引用数排名前 10 的推文。仅用于 Twitter。',
};
