import type { Language } from './contracts';
// Compact product descriptions for upstream cards and the graph table.
// These describe intended use, not observed crawler records or validated signals.
export const SOURCE_CARD_SUMMARIES: Record<string, readonly [string, string]> = {
  'binance.usdm.exchangeInfo': ['列出可交易合约，确定后续行情和持仓要跟踪的交易对。', 'List tradable contracts to choose pairs for price and position tracking.'],
  'binance.usdm.globalLongShortAccountRatio': ['查看多空账户比例，与价格和持仓变化对照。', 'Compare long and short account ratios with price and open interest.'],
  'binance.usdm.klines': ['提供价格和成交量 K 线，用于计算涨跌、放量和波动。', 'Use price and volume candles to measure returns, activity, and volatility.'],
  'binance.usdm.openInterest': ['读取当前未平仓量快照，连续采样后观察仓位变化。', 'Sample current open interest over time to track position changes.'],
  'binance.usdm.openInterestHist': ['读取未平仓量历史，与同期价格对齐分析仓位增减。', 'Align historical open interest with price to study position changes.'],
  'binance.usdm.premiumIndex': ['读取标记价格与资金费率，观察合约溢价和费率变化。', 'Track mark price, premium, and funding-rate changes.'],
  'binance.usdm.takerlongshortRatio': ['比较主动买卖成交量，观察短期交易方向。', 'Compare taker buy and sell volume for short-term direction.'],
  'binance.usdm.topLongShortAccountRatio': ['查看头部账户多空倾向，与全市场账户比例对照。', 'Compare top-trader account direction with the broader market.'],
  'binance.usdm.topLongShortPositionRatio': ['查看头部持仓多空比例，区分仓位与账户人数倾向。', 'Use top-trader position ratios to separate size from account counts.'],
  'coingecko.coins_markets': ['列出币种价格、市值和成交量，用于市场筛选与资产对齐。', 'Screen coins by price, market cap, and volume, then match asset IDs.'],
  'coingecko.search_trending': ['每30分钟观察过去24小时搜索热榜的默认15币，交给最热榜贡献规则；尚无本项目真实调用记录。', 'Observe the default 15 coins in the past-24-hour search trending list every 30 minutes for heat contributions; no project call has been observed.'],
  'dexscreener.token_pairs_by_address': ['按链和代币地址找交易池，比较流动性与成交活跃度。', 'Find token pools by chain and address; compare liquidity and trades.'],
  'kaito.mcp.kaito_entities': ['核对项目在 Kaito 的代币标识，供后续查询使用。', 'Resolve a project to its Kaito token ID before further queries.'],
  'kaito.mcp.kaito_narratives': ['确认叙事 ID，供叙事关注份额查询使用。', 'Resolve a narrative ID before querying its mindshare.'],
  'kaito.mcp.kaito_feeds': ['获取排序内容，作为市场动态线索并回查原文。', 'Review ranked market content, then verify the original posts.'],
  'kaito.mcp.kaito_search': ['按自然语言搜内容，收集帖子与新闻等候选证据。', 'Search posts and news in natural language for candidate evidence.'],
  'kaito.mcp.kaito_advanced_search': ['按对象、作者和时间筛内容，收集可核对的线索。', 'Filter content by entity, author, and time for reviewable leads.'],
  'kaito.mcp.kaito_twitter_user_metadata': ['查看 X 账号资料与粉丝规模，核对内容作者身份。', 'Check an X account profile and audience to identify an author.'],
  'kaito.mcp.kaito_ict_impressions': ['统计高影响力作者的内容曝光，比较不同时间窗的触达。', 'Compare tracked author impressions across time windows.'],
  'kaito.mcp.kaito_sentiment_entity': ['查看对象情绪走势，与历史基线及事件对照。', 'Compare entity sentiment over time with its baseline and events.'],
  'kaito.mcp.kaito_engagement': ['查看对象或关键词的每日互动量，识别讨论热度变化。', 'Track daily engagement for a token or keyword.'],
  'kaito.mcp.kaito_mentions': ['查看对象或主题每日提及量，衡量讨论规模变化。', 'Track daily mentions to measure changes in discussion volume.'],
  'kaito.mcp.kaito_mindshare_entity': ['查看对象讨论份额走势，观察相对关注度变化。', 'Track an entity’s share of discussion over time.'],
  'kaito.mcp.kaito_mindshare_entity_by_account': ['找出推动对象讨论份额的主要账号，再回看原文。', 'Find accounts contributing most to an entity’s discussion share.'],
  'kaito.mcp.kaito_events': ['列出项目候选催化事件，回查公告后设计提醒。', 'Review candidate catalysts against source announcements before alerts.'],
  'kaito.mcp.kaito_mindshare_entity_arena': ['按关注份额给对象排名，用于发现研究候选。', 'Rank entities by discussion share to find research candidates.'],
  'kaito.mcp.kaito_mindshare_entity_delta': ['找出关注份额变化最大的对象，再追查变化原因。', 'Find the largest mindshare changes, then investigate their causes.'],
  'kaito.mcp.kaito_smart_following_market': ['观察市场范围的高关注账号动向，并查看本次返回的对象。', 'Explore market-wide smart-follow activity and inspect the returned entities.'],
  'kaito.mcp.kaito_smart_followers': ['查看指定账号的高质量粉丝数量或名单，跟踪受众变化。', 'Check smart-follower counts or lists for an X account.'],
  'kaito.mcp.kaito_smart_following': ['查看指定账号最近关注谁，作为注意力变化线索。', 'See whom an X account recently followed as an attention clue.'],
  'kaito.mcp.kaito_mindshare_narrative': ['查看叙事讨论份额走势，比较主题关注度变化。', 'Track a narrative’s share of discussion over time.'],
  'kaito.mcp.kaito_market_sentiment': ['查看整体市场情绪，为单个对象情绪提供背景。', 'Use market-wide sentiment as context for entity sentiment.'],
  'kaito.mcp.kaito_tweet_engagement_info': ['读取单条推文的互动指标，分析内容传播表现。', 'Inspect engagement counts for one X post.'],
  'rss.item': ['读取订阅源新闻条目，作为事件线索并回查原文。', 'Read RSS news items as event leads and verify the source.'],
  'taoli.funding_page': ['读取页面资金费率表作候选来源；字段口径待核对。', 'Explore page funding rates; the field contract still needs review.'],
  'telegram.bot.message': ['接收 Bot 可见消息，按聊天与时间整理讨论线索。', 'Organize messages visible to a Bot by chat and time.'],
  'telegram.telethon.message': ['读取获准访问的频道消息，去重并回查原文。', 'Review accessible channel messages, deduplicate, and check originals.'],
  'kaito.resource.tokens': ['列出 Kaito 支持的代币标识，查询前用于身份核对。', 'Check supported Kaito token IDs before entity queries.'],
  'kaito.resource.narratives': ['列出 Kaito 支持的叙事 ID，查询前用于主题核对。', 'Check supported Kaito narrative IDs before topic queries.'],
};

export const sourceCardSummary = (name: string, language: Language) =>
  SOURCE_CARD_SUMMARIES[name]?.[language === 'zh-CN' ? 0 : 1] || null;
